-- Original, text-only questions on prescribed 2026–2030 WASSCE literature.
-- No quotations from the plays, novels or poems are used.
-- Re-running this file skips prompts already present for this subject.
begin;

do $guard$
begin
  if not exists (
    select 1 from public.subjects
    where id = '74d30747-d6fe-4ba3-aa2a-04a4c60577ff'::uuid
      and lower(exam_type::text) = 'waec'
  ) then
    raise exception 'Expected WAEC Literature in English subject is missing';
  end if;
end
$guard$;

with candidates (topic, prompt, options, correct_answer, explanation) as (
  values
  -- Antony and Cleopatra (18)
  ($q$Antony and Cleopatra$q$, $q$In Antony and Cleopatra, why does Antony's attachment to Egypt trouble his Roman allies?$q$, $q${"A":"They fear it weakens his attention to Roman political duties","B":"They think Egypt has no ruler","C":"They want him to abandon all military command","D":"They believe Cleopatra is a Roman senator"}$q$::jsonb, $q$A$q$, $q$Antony's Egyptian life appears to compete with the responsibilities and alliances expected of a Roman triumvir.$q$),
  ($q$Antony and Cleopatra$q$, $q$What political purpose does Antony's marriage to Octavia mainly serve?$q$, $q${"A":"It makes Cleopatra queen of Rome","B":"It tries to repair the alliance between Antony and Caesar","C":"It ends Rome's interest in Egypt","D":"It gives Octavia command of the fleet"}$q$::jsonb, $q$B$q$, $q$Octavia is Caesar's sister, so the marriage is intended to strengthen political trust between the men.$q$),
  ($q$Antony and Cleopatra$q$, $q$Why is the contrast between Rome and Egypt important to Antony's conflict?$q$, $q${"A":"Both settings demand identical behaviour","B":"Egypt has no political consequences","C":"They represent competing expectations of duty and desire","D":"Rome is never mentioned in the play"}$q$::jsonb, $q$C$q$, $q$Rome emphasizes public duty and political reputation, while Egypt is associated with Antony's personal attachment to Cleopatra.$q$),
  ($q$Antony and Cleopatra$q$, $q$Antony follows Cleopatra's retreat during the sea battle at Actium. What does this decision reveal?$q$, $q${"A":"His army has already won","B":"Caesar has surrendered","C":"Cleopatra controls the Roman Senate","D":"Private attachment can override military judgment"}$q$::jsonb, $q$D$q$, $q$Leaving the battle to follow Cleopatra shows how their relationship affects Antony's command.$q$),
  ($q$Antony and Cleopatra$q$, $q$Which character becomes Antony's chief Roman rival as their political alliance collapses?$q$, $q${"A":"Octavius Caesar","B":"Charmian","C":"Iras","D":"Octavia"}$q$::jsonb, $q$A$q$, $q$Octavius Caesar and Antony move from uneasy colleagues to opponents in the struggle for power.$q$),
  ($q$Antony and Cleopatra$q$, $q$Enobarbus leaves Antony but is deeply moved when Antony sends him his belongings. What does this response illuminate?$q$, $q${"A":"Enobarbus never admired Antony","B":"Loyalty and guilt complicate his desertion","C":"Antony intends to imprison him","D":"Caesar has left Rome"}$q$::jsonb, $q$B$q$, $q$Antony's generosity makes Enobarbus feel the moral cost of abandoning a leader he still values.$q$),
  ($q$Antony and Cleopatra$q$, $q$Why does Cleopatra fear being displayed in Caesar's Roman triumph?$q$, $q${"A":"She wants to command Caesar's army","B":"She has forgotten Egypt","C":"It would turn her defeat into public humiliation","D":"It would make her queen of Rome"}$q$::jsonb, $q$C$q$, $q$Being exhibited as a captive would deny Cleopatra control over her dignity and public image.$q$),
  ($q$Antony and Cleopatra$q$, $q$What false report contributes directly to Antony's decision to attempt suicide?$q$, $q${"A":"That Rome has vanished","B":"That Octavia has become queen","C":"That Enobarbus has won at Actium","D":"That Cleopatra is dead"}$q$::jsonb, $q$D$q$, $q$Antony acts after being told, wrongly, that Cleopatra has died.$q$),
  ($q$Antony and Cleopatra$q$, $q$Cleopatra chooses death rather than captivity after Antony's fall. Which theme is most strongly involved?$q$, $q${"A":"Control over honour and identity","B":"The invention of democracy","C":"The discovery of Egypt","D":"A peaceful Roman election"}$q$::jsonb, $q$A$q$, $q$Her final choice resists Caesar's power to define her as a conquered spectacle.$q$),
  ($q$Antony and Cleopatra$q$, $q$Why is Octavia's position especially difficult after the marriage?$q$, $q${"A":"She commands Cleopatra's palace","B":"She is caught between loyalty to her brother and her husband","C":"She is Caesar's enemy from the start","D":"She refuses all Roman customs"}$q$::jsonb, $q$B$q$, $q$Octavia is Caesar's sister and Antony's wife, making their political conflict a family conflict for her.$q$),
  ($q$Antony and Cleopatra$q$, $q$What does Antony's repeated concern for his reputation suggest about him?$q$, $q${"A":"He cares only about trade","B":"He has no military past","C":"Public honour remains important even amid personal conflict","D":"He wants to become an Egyptian priest"}$q$::jsonb, $q$C$q$, $q$Antony's Roman identity as a soldier and leader makes public honour a persistent concern.$q$),
  ($q$Antony and Cleopatra$q$, $q$Cleopatra's shifts between affection, anger and political caution make her best described as what?$q$, $q${"A":"A character without motives","B":"A silent observer","C":"A purely comic servant","D":"A complex, changing character"}$q$::jsonb, $q$D$q$, $q$Her behaviour has emotional and political dimensions, resisting a one-note reading.$q$),
  ($q$Antony and Cleopatra$q$, $q$Why does Caesar seek control over Cleopatra after Antony's defeat?$q$, $q${"A":"Her capture would strengthen his political triumph","B":"He wants her to lead his navy","C":"He plans to restore Antony's command","D":"He wants to abandon Rome"}$q$::jsonb, $q$A$q$, $q$A captive Cleopatra would visibly confirm Caesar's victory and enhance his standing.$q$),
  ($q$Antony and Cleopatra$q$, $q$What makes Antony's defeat tragic rather than merely a lost battle?$q$, $q${"A":"He never had any power","B":"His choices contribute to the destruction of his public standing and relationship","C":"Caesar never opposes him","D":"The play has no personal conflict"}$q$::jsonb, $q$B$q$, $q$The tragedy joins political ruin to Antony's own divided loyalties and decisions.$q$),
  ($q$Antony and Cleopatra$q$, $q$Enobarbus can criticize Antony while remaining attached to him. What dramatic function does this serve?$q$, $q${"A":"It proves Antony is faultless","B":"It removes the audience's need to judge","C":"It gives a perspective that recognizes both greatness and weakness","D":"It makes Enobarbus the ruler of Egypt"}$q$::jsonb, $q$C$q$, $q$Enobarbus's mixed response helps the audience assess Antony with both admiration and criticism.$q$),
  ($q$Antony and Cleopatra$q$, $q$What is the political significance of the Roman triumvirs' disagreements?$q$, $q${"A":"Rome has no government","B":"Egypt has joined the Senate","C":"All three have identical ambitions","D":"Shared rule can break down under competing ambitions"}$q$::jsonb, $q$D$q$, $q$The alliance is unstable because its powerful members compete for influence and trust.$q$),
  ($q$Antony and Cleopatra$q$, $q$Why is Cleopatra's royal position more than a romantic detail?$q$, $q${"A":"It makes her relationship with Antony part of international politics","B":"It makes her a Roman magistrate","C":"It ends Egypt's independence immediately","D":"It removes her ability to make choices"}$q$::jsonb, $q$A$q$, $q$As Egypt's ruler, Cleopatra's bond with Antony affects alliances and power between states.$q$),
  ($q$Antony and Cleopatra$q$, $q$Which opposition best captures a central tension in Antony's character?$q$, $q${"A":"Youth versus old age","B":"Roman public duty versus personal desire","C":"Poetry versus prose","D":"Riches versus poverty alone"}$q$::jsonb, $q$B$q$, $q$Antony is divided between the demands of Roman command and his attachment to Cleopatra.$q$),
  -- So the Path Does Not Die (8)
  ($q$So the Path Does Not Die$q$, $q$Why does Finaba's interrupted initiation alter her family's course?$q$, $q${"A":"It immediately makes her queen","B":"It ends all family ties forever","C":"Her father's intervention brings conflict with community expectations","D":"It sends her directly to a Roman court"}$q$::jsonb, $q$C$q$, $q$Stopping the ceremony challenges a valued custom and helps set the family on a new path.$q$),
  ($q$So the Path Does Not Die$q$, $q$Finaba grows from childhood in Sierra Leone into adult life abroad. What literary form does this journey suggest?$q$, $q${"A":"A courtroom transcript","B":"A single-scene farce","C":"An epic about ancient Rome","D":"A coming-of-age narrative"}$q$::jsonb, $q$D$q$, $q$The novel follows Finaba's development and changing understanding of herself over time.$q$),
  ($q$So the Path Does Not Die$q$, $q$What conflict is highlighted by Finaba's life between Sierra Leone and the United States?$q$, $q${"A":"Belonging across home and diaspora","B":"Competition for a Roman throne","C":"A murder investigation in Maycomb","D":"A battle for a Scottish crown"}$q$::jsonb, $q$A$q$, $q$Migration places Finaba between cultural expectations in her homeland and abroad.$q$),
  ($q$So the Path Does Not Die$q$, $q$Why does Finaba's father interrupt the initiation?$q$, $q${"A":"He wants to end all schooling","B":"He opposes the harmful practice involved","C":"He has been appointed colonial governor","D":"He wants her to join a political party"}$q$::jsonb, $q$B$q$, $q$His intervention expresses opposition to female genital cutting and concern for his daughter.$q$),
  ($q$So the Path Does Not Die$q$, $q$Finaba's grandmother defends the continuation of inherited customs. Which role does she play in the central debate?$q$, $q${"A":"A Roman ambassador","B":"A neutral narrator with no view","C":"A strong voice for tradition","D":"An American judge"}$q$::jsonb, $q$C$q$, $q$The grandmother's position brings the value and pressure of tradition into conflict with change.$q$),
  ($q$So the Path Does Not Die$q$, $q$Why is it too simple to say Finaba must choose either all tradition or all modernity?$q$, $q${"A":"The novel has no cultural setting","B":"She never questions her past","C":"Every custom is identical","D":"Her growth involves negotiating between them"}$q$::jsonb, $q$D$q$, $q$Finaba's identity develops through assessing inherited practices and new experiences rather than accepting one side uncritically.$q$),
  ($q$So the Path Does Not Die$q$, $q$How does the title connect to the novel's concern with cultural inheritance?$q$, $q${"A":"It raises the question of which traditions should continue or change","B":"It refers only to a road-construction contract","C":"It means Finaba never leaves home","D":"It names a military campaign"}$q$::jsonb, $q$A$q$, $q$The image of a continuing path invites reflection on preserving culture while confronting harmful practices.$q$),
  ($q$So the Path Does Not Die$q$, $q$Finaba's later decisions are shaped by memories of childhood events. Which narrative idea does this demonstrate?$q$, $q${"A":"Only future events matter","B":"The past continues to influence identity","C":"Characters cannot change","D":"Setting has no effect on character"}$q$::jsonb, $q$B$q$, $q$The interrupted initiation and its consequences remain important to Finaba's self-understanding.$q$),
  -- Redemption Road (8)
  ($q$Redemption Road$q$, $q$Bendu Lewis helps people affected by Liberia's civil war. Which theme does her work most clearly develop?$q$, $q${"A":"A struggle for Roman command","B":"A royal marriage bargain","C":"Healing after conflict","D":"A journey through ancient Egypt"}$q$::jsonb, $q$C$q$, $q$Bendu's work with survivors places recovery from war at the centre of the novel.$q$),
  ($q$Redemption Road$q$, $q$Why is the Liberian civil war essential to the novel rather than mere background scenery?$q$, $q${"A":"It creates a peaceful holiday","B":"It never affects any character","C":"It determines the price of a wedding","D":"Its violence shapes characters' memories and choices"}$q$::jsonb, $q$D$q$, $q$War trauma drives the personal and moral conflicts explored in the story.$q$),
  ($q$Redemption Road$q$, $q$What does Bendu's willingness to listen to survivors show about her?$q$, $q${"A":"Compassion joined to practical action","B":"Indifference to others' suffering","C":"A wish to rule by force","D":"A refusal to face the past"}$q$::jsonb, $q$A$q$, $q$She responds to others' pain by offering support rather than ignoring it.$q$),
  ($q$Redemption Road$q$, $q$Why might forgiveness in Redemption Road be difficult rather than automatic?$q$, $q${"A":"The conflict caused no harm","B":"Survivors carry serious memories of violence","C":"All characters agree about justice","D":"There are no former fighters"}$q$::jsonb, $q$B$q$, $q$The depth of wartime injury makes reconciliation a demanding moral process.$q$),
  ($q$Redemption Road$q$, $q$The novel places survivors and former perpetrators in one society after war. What question does this raise?$q$, $q${"A":"How to win a Roman sea battle","B":"How to appoint a Ghanaian chief","C":"How justice and reconciliation can coexist","D":"How to abolish all memory"}$q$::jsonb, $q$C$q$, $q$Postwar rebuilding requires dealing with responsibility while seeking a livable shared future.$q$),
  ($q$Redemption Road$q$, $q$Bendu is the central character through whom much of the postwar struggle is explored. What narrative role is this?$q$, $q${"A":"An unnamed chorus","B":"A comic servant only","C":"A distant historian","D":"Protagonist"}$q$::jsonb, $q$D$q$, $q$The protagonist is the central character whose experiences organize the narrative.$q$),
  ($q$Redemption Road$q$, $q$What makes hope meaningful in a story centered on war trauma?$q$, $q${"A":"It emerges despite suffering rather than denying it","B":"It proves no harm occurred","C":"It removes every difficult choice","D":"It requires the reader to forget the setting"}$q$::jsonb, $q$A$q$, $q$The novel's hopeful dimension matters because it coexists with acknowledged loss and injury.$q$),
  ($q$Redemption Road$q$, $q$Why can Bendu's care for individuals also be read as a comment on Liberia's recovery?$q$, $q${"A":"A nation is identical to one person","B":"Personal healing and social rebuilding are connected","C":"War has only private effects","D":"Public peace makes individual lives irrelevant"}$q$::jsonb, $q$B$q$, $q$The novel links survivors' recovery to the larger challenge of rebuilding a damaged society.$q$),
  -- To Kill a Mockingbird (12)
  ($q$To Kill a Mockingbird$q$, $q$Why does Atticus Finch agree to defend Tom Robinson despite local hostility?$q$, $q${"A":"He expects easy popularity","B":"He wants to stop all trials","C":"He believes legal duty and fairness matter","D":"He is Tom's brother"}$q$::jsonb, $q$C$q$, $q$Atticus acts from conscience and commitment to fair representation despite social pressure.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Scout's limited childhood understanding lets readers notice more than she initially understands. Which technique is involved?$q$, $q${"A":"An omniscient adult narrator only","B":"A courtroom transcript","C":"No narrator at all","D":"Child narration with dramatic irony"}$q$::jsonb, $q$D$q$, $q$Readers can infer social prejudice and adult motives beyond young Scout's immediate interpretation.$q$),
  ($q$To Kill a Mockingbird$q$, $q$What does Tom Robinson's trial expose about Maycomb society?$q$, $q${"A":"Racial prejudice can distort justice","B":"Courts never use witnesses","C":"Every resident rejects discrimination","D":"Children choose all verdicts"}$q$::jsonb, $q$A$q$, $q$The trial reveals how prejudice can outweigh evidence in legal judgment.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Why does Boo Radley matter to Scout's moral development?$q$, $q${"A":"He is the prosecutor at Tom's trial","B":"She learns to see him beyond fearful rumours","C":"He runs for mayor","D":"He writes the town's laws"}$q$::jsonb, $q$B$q$, $q$Scout's changing view of Boo teaches empathy and the danger of judging by gossip.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Jem becomes disillusioned by the trial's outcome. What has his expectation collided with?$q$, $q${"A":"A lack of any evidence","B":"His wish to leave Maycomb","C":"The gap between justice in principle and prejudice in practice","D":"A dispute about school holidays"}$q$::jsonb, $q$C$q$, $q$Jem expects evidence to guide the verdict but witnesses a prejudiced result.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Which act by Boo Radley most directly overturns the children's image of him as dangerous?$q$, $q${"A":"He accuses Tom Robinson","B":"He joins the jury","C":"He becomes a schoolteacher","D":"He protects Scout and Jem from an attack"}$q$::jsonb, $q$D$q$, $q$Boo's protection reveals kindness beneath the rumours that frightened the children.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Atticus asks his children to consider another person's point of view. Which central value does this teach?$q$, $q${"A":"Empathy","B":"Revenge","C":"Secrecy","D":"Social rank"}$q$::jsonb, $q$A$q$, $q$Empathy means trying to understand others' circumstances before judging them.$q$),
  ($q$To Kill a Mockingbird$q$, $q$The title's harmless bird is often read as symbolizing whom?$q$, $q${"A":"Only wealthy officials","B":"Innocent people harmed by cruelty or prejudice","C":"Only lawyers","D":"People who control the town"}$q$::jsonb, $q$B$q$, $q$The mockingbird image invites sympathy for innocents who cause no harm yet suffer from others.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Mayella Ewell's position is complicated because she is socially disadvantaged yet accuses Tom. What does this reveal?$q$, $q${"A":"Every character has equal power","B":"Poverty ends racial prejudice","C":"Different forms of power and disadvantage can coexist","D":"The trial has no social context"}$q$::jsonb, $q$C$q$, $q$Mayella's poverty does not erase the racial power she can exercise over Tom.$q$),
  ($q$To Kill a Mockingbird$q$, $q$Why is Atticus's courtroom effort still significant even though the verdict goes against Tom?$q$, $q${"A":"It proves prejudice is harmless","B":"It makes evidence unnecessary","C":"It guarantees a quick appeal","D":"It demonstrates principled resistance to injustice"}$q$::jsonb, $q$D$q$, $q$Atticus's defence tests the town's claims of fairness and models moral courage.$q$),
  ($q$To Kill a Mockingbird$q$, $q$What does Scout's narration add to the treatment of adult prejudice?$q$, $q${"A":"Her questions expose assumptions adults take for granted","B":"She knows every adult's private thoughts","C":"She prevents all conflict","D":"She is the judge at trial"}$q$::jsonb, $q$A$q$, $q$A child's perspective can make familiar adult prejudices appear strange and open to challenge.$q$),
  ($q$To Kill a Mockingbird$q$, $q$The jury's decision despite serious doubts about the accusation shows a conflict between what?$q$, $q${"A":"Two school subjects","B":"Evidence and entrenched bias","C":"Two foreign governments","D":"Comedy and tragedy only"}$q$::jsonb, $q$B$q$, $q$The trial dramatizes how bias can defeat evidence and fair procedure.$q$),
  -- Path of Lucas: The Journey He Endured (first 4 of 7)
  ($q$Path of Lucas: The Journey He Endured$q$, $q$Lucas sets aside a personal ambition to help his ill father and the family farm. Which quality is most visible?$q$, $q${"A":"Indifference","B":"Political ambition","C":"Family responsibility","D":"Fear of all work"}$q$::jsonb, $q$C$q$, $q$His choice puts family obligations before a preferred career path.$q$),
  ($q$Path of Lucas: The Journey He Endured$q$, $q$Why is Lucas's journey best read as more than a record of travel?$q$, $q${"A":"The story contains no places","B":"He never changes his mind","C":"It is a geography textbook","D":"The hardships test his commitments and character"}$q$::jsonb, $q$D$q$, $q$The journey is also emotional and moral, as Lucas responds to repeated family difficulties.$q$),
  ($q$Path of Lucas: The Journey He Endured$q$, $q$When Lucas cares for Isabelle during serious illness, what theme is reinforced?$q$, $q${"A":"Love expressed through sacrifice","B":"The failure of all family bonds","C":"Competition for a throne","D":"A courtroom's racial injustice"}$q$::jsonb, $q$A$q$, $q$His practical care for Isabelle shows devotion through costly action.$q$),
  ($q$Path of Lucas: The Journey He Endured$q$, $q$The novel follows Lucas from a small Ontario community through changing family circumstances. What role does setting play?$q$, $q${"A":"It replaces every character","B":"It grounds his choices in work and family life","C":"It makes the story an ancient myth","D":"It removes all conflict"}$q$::jsonb, $q$B$q$, $q$The rural background helps explain Lucas's work, responsibilities and sacrifices.$q$),
  ($q$Path of Lucas: The Journey He Endured$q$, $q$Lucas's responsibilities repeatedly interrupt his preferred plans. Which conflict does this create?$q$, $q${"A":"A dispute over a royal crown","B":"A trial for a crime","C":"Personal ambition against family duty","D":"A war between nations"}$q$::jsonb, $q$C$q$, $q$His aspirations compete with the practical needs of people close to him.$q$),
  ($q$Path of Lucas: The Journey He Endured$q$, $q$What is the effect of showing Lucas make difficult choices rather than merely describing him as loyal?$q$, $q${"A":"It makes the narrator disappear","B":"It removes all suspense","C":"It changes prose into poetry","D":"His actions make his loyalty credible"}$q$::jsonb, $q$D$q$, $q$Character is revealed through decisions and their consequences, not only through labels.$q$),
  ($q$Path of Lucas: The Journey He Endured$q$, $q$Why is resilience a suitable theme for Lucas's story?$q$, $q${"A":"He continues to face hardship without abandoning those who depend on him","B":"He never encounters a setback","C":"He wins a parliamentary election","D":"He controls every event around him"}$q$::jsonb, $q$A$q$, $q$Resilience is the capacity to continue purposeful action under pressure.$q$),
  -- Once Upon an Elephant (8)
  ($q$Once Upon an Elephant$q$, $q$Why is Ajanaku's installation as ruler controversial at the start of Once Upon an Elephant?$q$, $q${"A":"He refuses the title offered to him","B":"The reigning king is still alive and the usual process is bypassed","C":"He has been elected by universal ballot","D":"The village has no royal tradition"}$q$::jsonb, $q$B$q$, $q$Serubawon advances Ajanaku while King Akinjobi is ill but still alive, provoking objections to the irregular succession.$q$),
  ($q$Once Upon an Elephant$q$, $q$What is Serubawon's role in Ajanaku's rise?$q$, $q${"A":"He leads the public opposition","B":"He withdraws from the community","C":"He manipulates the kingmaking process to favour Ajanaku","D":"He is the reigning king whom Ajanaku replaces"}$q$::jsonb, $q$C$q$, $q$Serubawon pushes Ajanaku's accession despite objections from other elders.$q$),
  ($q$Once Upon an Elephant$q$, $q$Ajanaku's conduct is best used to explore which theme?$q$, $q${"A":"The joys of agricultural labour","B":"The benefits of isolation","C":"The absence of political conflict","D":"The corruption of power"}$q$::jsonb, $q$D$q$, $q$His exercise of authority raises questions about tyranny and moral restraint.$q$),
  ($q$Once Upon an Elephant$q$, $q$What role does Iya Agba play when she confronts Ajanaku?$q$, $q${"A":"She challenges his conduct and claims to authority","B":"She confirms that every judgment he makes is fair","C":"She serves only as a foreign ambassador","D":"She removes all opposition to him"}$q$::jsonb, $q$A$q$, $q$Iya Agba speaks against the ruler and unsettles the story used to justify his power.$q$),
  ($q$Once Upon an Elephant$q$, $q$How does Ajanaku handle a disputed piece of land brought before him?$q$, $q${"A":"He orders an impartial hearing by another court","B":"He claims the disputed land for himself","C":"He returns it to both claimants equally","D":"He asks the claimants to leave the village"}$q$::jsonb, $q$B$q$, $q$The land dispute exposes his greed because he uses judgment to take the land.$q$),
  ($q$Once Upon an Elephant$q$, $q$Why does Odejimi resist the rushed enthronement?$q$, $q${"A":"He wants the village abolished","B":"He opposes all traditions","C":"He questions the irregular succession while Akinjobi is alive","D":"He is Ajanaku's foreign ally"}$q$::jsonb, $q$C$q$, $q$Odejimi objects to Serubawon's attempt to sidestep the accepted process.$q$),
  ($q$Once Upon an Elephant$q$, $q$If a ruler is praised publicly while subjects privately fear him, what device is at work?$q$, $q${"A":"Onomatopoeia alone","B":"A flashback without contrast","C":"A literal stage direction only","D":"Irony between public praise and private reality"}$q$::jsonb, $q$D$q$, $q$The contrast between what is said and what people experience creates irony.$q$),
  ($q$Once Upon an Elephant$q$, $q$What does Ajanaku's harsh treatment of dissenters suggest about his leadership?$q$, $q${"A":"He treats disagreement as a threat rather than a check on power","B":"He protects every critic from punishment","C":"He submits each complaint to an independent court","D":"He willingly surrenders royal authority"}$q$::jsonb, $q$A$q$, $q$His response to opposition reveals a tyrannical view of authority.$q$),
  -- The Marriage of Anansewa (8)
  ($q$The Marriage of Anansewa$q$, $q$Why does Ananse seek several potential husbands for Anansewa at once?$q$, $q${"A":"He wants to end marriage entirely","B":"He hopes to profit from competing offers","C":"He has forgotten who his daughter is","D":"He is arranging a political election"}$q$::jsonb, $q$B$q$, $q$Ananse courts several suitors and their support, creating the play's central deception.$q$),
  ($q$The Marriage of Anansewa$q$, $q$Ananse's treatment of Anansewa raises which ethical question?$q$, $q${"A":"Whether every suitor lives abroad","B":"Whether storytelling can use songs","C":"Whether a parent's financial goals should override a child's choice","D":"Whether a stage needs scenery"}$q$::jsonb, $q$C$q$, $q$His schemes place parental authority and material gain against Anansewa's agency.$q$),
  ($q$The Marriage of Anansewa$q$, $q$What most directly creates comic suspense when multiple chiefs seek Anansewa?$q$, $q${"A":"The total absence of secrets","B":"The arrival of a police inspector","C":"A battle at sea","D":"Ananse's need to keep his contradictory arrangements apart"}$q$::jsonb, $q$D$q$, $q$His overlapping promises threaten to expose him and drive the comedy.$q$),
  ($q$The Marriage of Anansewa$q$, $q$What does the storytelling form add to the play?$q$, $q${"A":"A direct relationship between storyteller and audience","B":"A guarantee that events are historical records","C":"The removal of humour","D":"A complete ban on music"}$q$::jsonb, $q$A$q$, $q$The play draws on oral storytelling conventions that engage the audience in the action.$q$),
  ($q$The Marriage of Anansewa$q$, $q$Why can Ananse be amusing and morally questionable at the same time?$q$, $q${"A":"He never makes plans","B":"His clever improvisation serves a selfish deception","C":"He cannot speak to the audience","D":"His schemes harm no one"}$q$::jsonb, $q$B$q$, $q$Comedy does not erase the ethical problem of manipulating his daughter and suitors.$q$),
  ($q$The Marriage of Anansewa$q$, $q$The suitors' gifts and promises mainly expose what tension?$q$, $q${"A":"Weather against farming","B":"Poetry against prose","C":"Marriage as personal relationship versus material transaction","D":"Science against religion"}$q$::jsonb, $q$C$q$, $q$Material advantage becomes entangled with the choice of a spouse.$q$),
  ($q$The Marriage of Anansewa$q$, $q$When the audience knows more about Ananse's plans than a suitor does, which device helps produce humour?$q$, $q${"A":"A scientific demonstration","B":"An epic simile only","C":"A chorus with no information","D":"Dramatic irony"}$q$::jsonb, $q$D$q$, $q$The gap between audience knowledge and a character's knowledge creates dramatic irony.$q$),
  ($q$The Marriage of Anansewa$q$, $q$How does Anansewa's position complicate the apparent success of her father's plans?$q$, $q${"A":"Her wishes and future are at stake in his bargain","B":"She is unrelated to the marriage","C":"She is one of the chiefs","D":"She controls the national treasury"}$q$::jsonb, $q$A$q$, $q$The scheme concerns a real person's marriage, not just Ananse's cleverness.$q$),
  -- An Inspector Calls (12)
  ($q$An Inspector Calls$q$, $q$Why does the Inspector question the Birling family about Eva Smith?$q$, $q${"A":"She has been elected mayor","B":"Their separate actions may have contributed to her suffering","C":"She owns their factory","D":"She invited them to a wedding"}$q$::jsonb, $q$B$q$, $q$The inquiry links apparently separate choices to one woman's desperate situation.$q$),
  ($q$An Inspector Calls$q$, $q$Mr Birling's confidence in his own predictions is undercut by the audience's knowledge of later history. What device is this?$q$, $q${"A":"Personification","B":"Alliteration","C":"Dramatic irony","D":"A soliloquy"}$q$::jsonb, $q$C$q$, $q$An audience aware of later events can see errors in his confident claims.$q$),
  ($q$An Inspector Calls$q$, $q$Why is Sheila's response to the investigation different from her parents'?$q$, $q${"A":"She denies ever meeting anyone","B":"She thinks wealth settles responsibility","C":"She orders the Inspector away","D":"She increasingly accepts responsibility for her behaviour"}$q$::jsonb, $q$D$q$, $q$Sheila's willingness to reflect contrasts with her parents' defensive concern for reputation.$q$),
  ($q$An Inspector Calls$q$, $q$What does Eva Smith represent in the play beyond one individual?$q$, $q${"A":"Vulnerable workers affected by more powerful people's choices","B":"A royal family member","C":"The owner of the Birling business","D":"A supernatural judge"}$q$::jsonb, $q$A$q$, $q$Eva's experiences connect class, work and social responsibility.$q$),
  ($q$An Inspector Calls$q$, $q$Why does the family's possible discovery that the Inspector is not a police officer fail to settle the play's ethical question?$q$, $q${"A":"Eva becomes wealthy","B":"Their treatment of Eva still has moral consequences","C":"The factory closes at once","D":"Sheila forgets the evening"}$q$::jsonb, $q$B$q$, $q$The truth of their actions matters even if the visitor's official status is uncertain.$q$),
  ($q$An Inspector Calls$q$, $q$How does the confined dining-room setting assist the drama?$q$, $q${"A":"It hides every family member","B":"It prevents dialogue","C":"It intensifies the family's confrontation with their conduct","D":"It turns the play into a sea voyage"}$q$::jsonb, $q$C$q$, $q$Keeping the family together while revelations unfold heightens pressure and tension.$q$),
  ($q$An Inspector Calls$q$, $q$What is the significance of Gerald's connection with Daisy Renton?$q$, $q${"A":"It proves he owns Eva's workplace","B":"It removes him from the investigation","C":"It makes him the Inspector's brother","D":"It links his apparently respectable life to Eva's story"}$q$::jsonb, $q$D$q$, $q$The relationship complicates the family's self-image and draws Gerald into the inquiry.$q$),
  ($q$An Inspector Calls$q$, $q$Why is Mrs Birling's refusal to help Eva particularly ironic?$q$, $q${"A":"She chairs a charity meant to help people in need","B":"She works as Eva's schoolteacher","C":"She has never met a poor person","D":"She is the only factory employee"}$q$::jsonb, $q$A$q$, $q$Her charitable position contrasts with her harsh judgment of an applicant in distress.$q$),
  ($q$An Inspector Calls$q$, $q$Which contrast is central to the Inspector's challenge to Mr Birling?$q$, $q${"A":"Country life versus city life","B":"Individual self-interest versus shared social responsibility","C":"Science versus superstition","D":"Youth versus age alone"}$q$::jsonb, $q$B$q$, $q$The Inspector argues that people's lives are connected, opposing Birling's narrow self-interest.$q$),
  ($q$An Inspector Calls$q$, $q$What does Eric's confession add to the family's crisis?$q$, $q${"A":"It proves the Inspector is a relative","B":"It ends Eva's difficulties before they begin","C":"It shows even the youngest generation has contributed to Eva's plight","D":"It makes Eva the factory owner"}$q$::jsonb, $q$C$q$, $q$Eric's conduct and misuse of money extend the chain of responsibility.$q$),
  ($q$An Inspector Calls$q$, $q$Why is the final telephone call dramatically effective?$q$, $q${"A":"It reports a happy marriage","B":"It confirms every earlier prediction","C":"It cancels the events of the evening","D":"It reopens the question of investigation just as the family relaxes"}$q$::jsonb, $q$D$q$, $q$The call reverses their relief and forces renewed attention to responsibility.$q$),
  ($q$An Inspector Calls$q$, $q$How does Priestley use the family's differing reactions to the Inspector's departure?$q$, $q${"A":"To show that remorse and concern for reputation are not the same","B":"To prove all characters respond identically","C":"To remove the theme of class","D":"To show Eva controlled the inquiry"}$q$::jsonb, $q$A$q$, $q$Some characters retain moral concern while others focus on escaping public embarrassment.$q$),
  -- A Man for All Seasons (9)
  ($q$A Man for All Seasons$q$, $q$Why does Thomas More refuse to approve Henry VIII's disputed marriage arrangements?$q$, $q${"A":"He wants to become king","B":"He will not publicly violate his conscience","C":"He is seeking command of the army","D":"He has never met Henry"}$q$::jsonb, $q$B$q$, $q$More's conflict arises from the tension between royal demands and his own convictions.$q$),
  ($q$A Man for All Seasons$q$, $q$What does More's silence mainly represent in his conflict with the authorities?$q$, $q${"A":"Complete agreement with the king","B":"Forgetfulness about the issue","C":"A legal and moral attempt not to affirm what he rejects","D":"A plan to seize power"}$q$::jsonb, $q$C$q$, $q$He uses silence to avoid an explicit oath or statement against his conscience.$q$),
  ($q$A Man for All Seasons$q$, $q$Richard Rich's choices contrast with More's because Rich is especially driven by what?$q$, $q${"A":"A wish to abandon society","B":"A plan to restore Rome","C":"A fear of public speaking","D":"Ambition and advancement"}$q$::jsonb, $q$D$q$, $q$Rich's pursuit of position contrasts with More's refusal to trade conscience for advantage.$q$),
  ($q$A Man for All Seasons$q$, $q$Why is the law important to More even when its protection becomes uncertain?$q$, $q${"A":"He values legal safeguards for everyone, not only himself","B":"He believes law makes kings unnecessary","C":"He wants to write a comedy","D":"He thinks every verdict must favour him"}$q$::jsonb, $q$A$q$, $q$More insists on legal principle as a protection against arbitrary power.$q$),
  ($q$A Man for All Seasons$q$, $q$What does the play suggest about the cost of remaining faithful to conscience?$q$, $q${"A":"It always brings immediate promotion","B":"It may require sacrifice of safety and status","C":"It prevents all conflict","D":"It guarantees political victory"}$q$::jsonb, $q$B$q$, $q$More's principled refusal brings loss of office, imprisonment and death.$q$),
  ($q$A Man for All Seasons$q$, $q$How does the Common Man help frame the audience's view of More?$q$, $q${"A":"He replaces More as king","B":"He is a silent figure throughout","C":"His shifting ordinary roles contrast survival and compromise with principle","D":"He leads More's army"}$q$::jsonb, $q$C$q$, $q$The Common Man's various roles and compromises provide a foil to More's consistency.$q$),
  ($q$A Man for All Seasons$q$, $q$What pressure does Thomas Cromwell apply to More?$q$, $q${"A":"He asks More to leave England as a tourist","B":"He invites More to direct a play","C":"He gives More command of the navy","D":"He seeks More's submission to the king's position"}$q$::jsonb, $q$D$q$, $q$Cromwell works to secure compliance with the monarch's religious and political demands.$q$),
  ($q$A Man for All Seasons$q$, $q$Why does More's family matter to the moral conflict?$q$, $q${"A":"His choice endangers people he loves, making principle personally costly","B":"His family has no knowledge of events","C":"They control the royal court","D":"They write the oath for him"}$q$::jsonb, $q$A$q$, $q$The effects on wife and daughter intensify the cost of his stand.$q$),
  ($q$A Man for All Seasons$q$, $q$More's refusal to condemn others for choosing differently chiefly shows what?$q$, $q${"A":"He considers conscience unimportant","B":"He distinguishes his own duty from other people's decisions","C":"He believes the king has abdicated","D":"He wants to stop every trial"}$q$::jsonb, $q$B$q$, $q$More tries to remain true to his convictions without forcing others to make his choice.$q$),
  -- African poetry: five original analytical prompts for each listed poem
  ($q$Once Upon a Time$q$, $q$In Gabriel Okara's Once Upon a Time, what change troubles the speaker most?$q$, $q${"A":"The disappearance of schools","B":"The loss of daylight","C":"The replacement of sincere warmth with social pretence","D":"The arrival of foreign ships"}$q$::jsonb, $q$C$q$, $q$The speaker contrasts genuine feeling in the past with rehearsed, insincere behaviour in the present.$q$),
  ($q$Once Upon a Time$q$, $q$Why does the speaker address a child?$q$, $q${"A":"To ask for financial help","B":"To report a crime","C":"To end their relationship","D":"To recover a model of unguarded sincerity"}$q$::jsonb, $q$D$q$, $q$The child represents a more natural honesty that the adult wishes to relearn.$q$),
  ($q$Once Upon a Time$q$, $q$What is the effect of contrasting outward smiles with inward feelings?$q$, $q${"A":"It exposes the gap between appearance and sincerity","B":"It proves all greetings are truthful","C":"It establishes a scientific law","D":"It eliminates the speaker's regret"}$q$::jsonb, $q$A$q$, $q$The contrast highlights social masks rather than genuine affection.$q$),
  ($q$Once Upon a Time$q$, $q$Which reading best explains the poem's recurring movement between past and present?$q$, $q${"A":"The speaker cannot remember any event","B":"It measures the speaker's sense of moral loss","C":"It predicts a particular election","D":"It describes two unrelated families"}$q$::jsonb, $q$B$q$, $q$Repeated comparisons make a change in human relationships the centre of the poem.$q$),
  ($q$Once Upon a Time$q$, $q$The adult's wish to relearn genuine laughter suggests what?$q$, $q${"A":"The child must become less honest","B":"The past can be restored exactly","C":"The speaker is dissatisfied with learned pretence","D":"Laughter has no emotional meaning"}$q$::jsonb, $q$C$q$, $q$The speaker sees artificial politeness as learned behaviour that should be unlearned.$q$),
  ($q$New Tongue$q$, $q$In Elizabeth L.A. Kamara's New Tongue, what is the central concern about a younger generation?$q$, $q${"A":"They cannot learn new skills","B":"They have no interest in travel","C":"They are unable to speak at all","D":"They neglect inherited language and cultural bonds"}$q$::jsonb, $q$D$q$, $q$The poem worries that attachment to a borrowed culture weakens family and traditional ties.$q$),
  ($q$New Tongue$q$, $q$Why does the poem link changes in speech with changes in behaviour?$q$, $q${"A":"Language is presented as part of cultural identity","B":"Speech has no relation to culture","C":"The speaker is teaching spelling","D":"All cultural change is described as harmless"}$q$::jsonb, $q$A$q$, $q$A new way of speaking becomes a sign of deeper shifts in loyalty and identity.$q$),
  ($q$New Tongue$q$, $q$The poem's attention to weakened family ties chiefly develops which theme?$q$, $q${"A":"Military victory","B":"Generational estrangement","C":"Commercial farming","D":"A courtroom trial"}$q$::jsonb, $q$B$q$, $q$It portrays distance between younger people and the elders and traditions that formed them.$q$),
  ($q$New Tongue$q$, $q$What does the idea of a borrowed culture imply in the poem?$q$, $q${"A":"Every culture has the same history","B":"Tradition has already disappeared everywhere","C":"The new identity is adopted from elsewhere rather than inherited locally","D":"Speech can never change"}$q$::jsonb, $q$C$q$, $q$The speaker contrasts imported habits with the community's own heritage.$q$),
  ($q$New Tongue$q$, $q$Which tension would a discussion of New Tongue need to address?$q$, $q${"A":"Agriculture versus mining","B":"Dawn versus midnight","C":"Comedy versus tragedy","D":"Attraction to new ways versus preservation of communal memory"}$q$::jsonb, $q$D$q$, $q$The poem examines what may be lost when novelty displaces inherited bonds.$q$),
  ($q$Night$q$, $q$In Wole Soyinka's Night, why is night more than a neutral time of day?$q$, $q${"A":"It acts as a powerful presence pressing on the speaker","B":"It is used only to give a date","C":"It has no effect on mood","D":"It names a human character in a courtroom"}$q$::jsonb, $q$A$q$, $q$The speaker addresses night as an active force, giving the setting emotional power.$q$),
  ($q$Night$q$, $q$What does addressing night directly contribute to the poem?$q$, $q${"A":"It removes the speaker from the poem","B":"It personifies night and makes the conflict immediate","C":"It turns the poem into a newspaper report","D":"It fixes the poem's exact year"}$q$::jsonb, $q$B$q$, $q$Direct address treats night as a responsive presence rather than mere background.$q$),
  ($q$Night$q$, $q$The speaker's unease amid shadow and sea imagery mainly creates what mood?$q$, $q${"A":"Carefree celebration","B":"Comic surprise","C":"Vulnerability and apprehension","D":"Administrative calm"}$q$::jsonb, $q$C$q$, $q$The sensory landscape conveys pressure and uncertainty rather than ease.$q$),
  ($q$Night$q$, $q$What is achieved by combining bodily sensation with the surrounding landscape?$q$, $q${"A":"The landscape becomes irrelevant","B":"The speaker becomes omniscient","C":"The poem becomes a farming manual","D":"Outer darkness is felt as an inner experience"}$q$::jsonb, $q$D$q$, $q$Images of touch and setting make night both physical and psychological.$q$),
  ($q$Night$q$, $q$Why is a purely literal reading of Night incomplete?$q$, $q${"A":"The night also carries fear and emotional intensity","B":"It has no references to darkness","C":"It describes only a named battle","D":"Its speaker never responds to the setting"}$q$::jsonb, $q$A$q$, $q$The poem uses the natural scene to express the speaker's disturbed state.$q$),
  ($q$Not My Business$q$, $q$In Niyi Osundare's Not My Business, what attitude does the speaker initially show to other people's suffering?$q$, $q${"A":"Collective action","B":"Self-protective indifference","C":"Public confession","D":"Active rescue"}$q$::jsonb, $q$B$q$, $q$The speaker repeatedly treats oppression as irrelevant while personally safe.$q$),
  ($q$Not My Business$q$, $q$Why is the final threat to the speaker important?$q$, $q${"A":"It proves oppression ended","B":"It introduces a new narrator with no link to earlier events","C":"It shows that ignoring injustice does not guarantee safety","D":"It turns the poem into a celebration"}$q$::jsonb, $q$C$q$, $q$The danger eventually reaches the formerly indifferent observer.$q$),
  ($q$Not My Business$q$, $q$What does the repeated return to the speaker's own comfort emphasize?$q$, $q${"A":"The speaker's generosity","B":"The state's fairness","C":"The certainty of protection","D":"A narrow concern for personal survival"}$q$::jsonb, $q$D$q$, $q$Repetition exposes how material comfort supports the speaker's refusal to care.$q$),
  ($q$Not My Business$q$, $q$The different victims in the poem chiefly suggest what?$q$, $q${"A":"Arbitrary repression can reach many kinds of people","B":"Only one occupation is in danger","C":"All victims deserve their treatment","D":"The speaker knows each victim personally"}$q$::jsonb, $q$A$q$, $q$The varied examples broaden the warning beyond a single person's case.$q$),
  ($q$Not My Business$q$, $q$Which civic lesson is most consistent with the poem?$q$, $q${"A":"Silence always protects the innocent","B":"Solidarity matters when others face injustice","C":"Only officials should notice abuse","D":"Private meals are more important than rights"}$q$::jsonb, $q$B$q$, $q$The ending challenges passive self-interest and invites concern for others.$q$),
  ($q$Hearty Garlands$q$, $q$In S.O.H. Afriyie-Vidza's Hearty Garlands, the addressed elder is mainly honoured for what?$q$, $q${"A":"Winning a war","B":"Holding royal office","C":"A life of achievement and mentorship","D":"Owning a fleet of ships"}$q$::jsonb, $q$C$q$, $q$The poem celebrates an older figure's work and influence on younger people.$q$),
  ($q$Hearty Garlands$q$, $q$Why does the poem acknowledge envy amid praise?$q$, $q${"A":"To cancel the celebration","B":"To accuse the elder of dishonesty","C":"To change the poem's subject","D":"To admit mixed human feelings while still offering tribute"}$q$::jsonb, $q$D$q$, $q$The speaker recognizes that admiration can coexist with envy, making the praise less simplistic.$q$),
  ($q$Hearty Garlands$q$, $q$What does the garland image contribute to the poem?$q$, $q${"A":"It makes affection and honour concrete","B":"It proves the elder is a gardener","C":"It describes a prison sentence","D":"It removes the idea of celebration"}$q$::jsonb, $q$A$q$, $q$A garland is a fitting symbol of public tribute and affection.$q$),
  ($q$Hearty Garlands$q$, $q$How is old age treated in the poem?$q$, $q${"A":"As proof that hope is impossible","B":"As a stage of continued dignity and possible purpose","C":"As an occasion for mockery only","D":"As an unimportant biographical fact"}$q$::jsonb, $q$B$q$, $q$The poem honours past achievement while still urging the elder toward life ahead.$q$),
  ($q$Hearty Garlands$q$, $q$What relationship is implied by the speakers' affectionate address to their mentor?$q$, $q${"A":"A legal dispute","B":"A military command","C":"Gratitude across generations","D":"A commercial sale"}$q$::jsonb, $q$C$q$, $q$The tribute connects the elder's example with those who have learned from him.$q$),
  ($q$The Breast of the Sea$q$, $q$In Syl Cheney-Coker's The Breast of the Sea, why is the sea presented as bearing the weight of history?$q$, $q${"A":"It has no link to human experience","B":"It is only a holiday setting","C":"It names a single ship","D":"It gathers memories of violence, travel and suffering"}$q$::jsonb, $q$D$q$, $q$The sea becomes a witness to many human events and losses.$q$),
  ($q$The Breast of the Sea$q$, $q$What does the poem's questioning of the sea's power to heal suggest?$q$, $q${"A":"Comfort may be inadequate after severe collective trauma","B":"The sea caused every historical event","C":"The speaker expects a scientific answer","D":"All suffering has ended"}$q$::jsonb, $q$A$q$, $q$The speaker doubts whether consolation can answer the scale of violence described.$q$),
  ($q$The Breast of the Sea$q$, $q$The sea's human-like body in the poem is an example of what?$q$, $q${"A":"A literal medical description","B":"Personification","C":"A stage direction","D":"A legal definition"}$q$::jsonb, $q$B$q$, $q$Attributing human features and capacities to the sea is personification.$q$),
  ($q$The Breast of the Sea$q$, $q$Why does the poem combine ecological damage with human violence?$q$, $q${"A":"To prove nature is separate from history","B":"To avoid moral judgment","C":"To show a world wounded by connected forms of harm","D":"To list only scientific measurements"}$q$::jsonb, $q$C$q$, $q$Environmental and human suffering are brought together in its troubled vision.$q$),
  ($q$The Breast of the Sea$q$, $q$What effect does the movement across different places and historical references create?$q$, $q${"A":"It confines the poem to one private room","B":"It erases the speaker's concern","C":"It proves all events happened in one year","D":"It broadens the poem's scale beyond one nation"}$q$::jsonb, $q$D$q$, $q$The range of references makes the sea a setting for global memory and injury.$q$),
  -- Non-African poetry: five original analytical prompts for each listed poem
  ($q$She Walks in Beauty$q$, $q$In Lord Byron's She Walks in Beauty, what is the effect of bringing light and darkness together?$q$, $q${"A":"Their balance expresses the woman's harmonious beauty","B":"It proves the poem takes place at noon","C":"It describes a storm at sea","D":"It suggests the speaker cannot see her"}$q$::jsonb, $q$A$q$, $q$Contrasting light and dark are presented as complementary qualities of her appearance.$q$),
  ($q$She Walks in Beauty$q$, $q$Why does the poem move from physical appearance to the woman's thoughts and character?$q$, $q${"A":"To abandon its subject","B":"To connect outward grace with inward goodness","C":"To identify a historical battle","D":"To imply beauty has no moral dimension"}$q$::jsonb, $q$B$q$, $q$The speaker reads her serene appearance as expressing a peaceful inner life.$q$),
  ($q$She Walks in Beauty$q$, $q$The measured, admiring tone is most consistent with what view of the subject?$q$, $q${"A":"Open hostility","B":"Comic ridicule","C":"Idealized appreciation","D":"Political suspicion"}$q$::jsonb, $q$C$q$, $q$The speaker celebrates the woman's balanced beauty and moral calm.$q$),
  ($q$She Walks in Beauty$q$, $q$What would be lost if the poem described only brightness without its contrast?$q$, $q${"A":"Every reference to a person","B":"The fact that it is a poem","C":"The setting of a courtroom","D":"The sense that beauty arises from a delicate balance"}$q$::jsonb, $q$D$q$, $q$The interplay of opposites is central to the portrait's harmony.$q$),
  ($q$She Walks in Beauty$q$, $q$Which feature most clearly makes the poem a lyric of praise?$q$, $q${"A":"A speaker's concentrated admiration of one person","B":"A sequence of stage directions","C":"A formal legal judgment","D":"A list of prices"}$q$::jsonb, $q$A$q$, $q$The short poem develops one speaker's personal appreciation of the woman.$q$),
  ($q$The Nun's Priest's Tale$q$, $q$In the shortened Nun's Priest's Tale, why does making birds speak matter?$q$, $q${"A":"It proves the birds are historical rulers","B":"It lets animal characters display human pride and judgment","C":"It removes all humour","D":"It makes the widow disappear"}$q$::jsonb, $q$B$q$, $q$The talking animals act out recognizably human weaknesses in a comic narrative.$q$),
  ($q$The Nun's Priest's Tale$q$, $q$What is the function of the widow's modest home at the start of the tale?$q$, $q${"A":"It marks her as a queen","B":"It gives the tale no social setting","C":"It contrasts simple domestic life with the grand style used for the cock","D":"It places the action in a palace"}$q$::jsonb, $q$C$q$, $q$The elaborate treatment of an ordinary farmyard bird is humorous against a humble background.$q$),
  ($q$The Nun's Priest's Tale$q$, $q$Why does the narrator describe Chanticleer in elevated terms?$q$, $q${"A":"To deny he is an animal","B":"To make him a military officer","C":"To avoid all characterization","D":"To comically magnify an ordinary farmyard cock"}$q$::jsonb, $q$D$q$, $q$Grand descriptions of a familiar bird create mock-heroic humour.$q$),
  ($q$The Nun's Priest's Tale$q$, $q$What does the tale's treatment of animal conversation invite readers to consider?$q$, $q${"A":"Human behaviour through a humorous animal world","B":"The exact market value of eggs","C":"A rule of scientific classification only","D":"The date of a royal coronation"}$q$::jsonb, $q$A$q$, $q$Animals with human speech and concerns let the tale satirize people indirectly.$q$),
  ($q$The Nun's Priest's Tale$q$, $q$Which contrast best explains the tale's mock-heroic effect?$q$, $q${"A":"A city versus a village only","B":"Lofty storytelling language applied to a farmyard scene","C":"Poetry versus all prose","D":"Past tense versus present tense"}$q$::jsonb, $q$B$q$, $q$The style sounds grander than its everyday subject, producing comedy.$q$),
  ($q$Digging$q$, $q$In Seamus Heaney's Digging, how does the speaker's work differ from his father and grandfather's?$q$, $q${"A":"He farms more land","B":"He mines stone","C":"He writes rather than works the soil","D":"He sells agricultural tools"}$q$::jsonb, $q$C$q$, $q$The speaker honours family labour while choosing writing as his own craft.$q$),
  ($q$Digging$q$, $q$Why are detailed memories of manual work important to the poem?$q$, $q${"A":"They mock the speaker's family","B":"They show the speaker has forgotten his roots","C":"They provide irrelevant scenery","D":"They express respect for skill passed through generations"}$q$::jsonb, $q$D$q$, $q$The precision of remembered labour shows admiration for his father and grandfather.$q$),
  ($q$Digging$q$, $q$What does the speaker's writing instrument become at the end of the poem?$q$, $q${"A":"A figurative tool for doing his own kind of work","B":"A literal farm spade","C":"A weapon used in battle","D":"A symbol of abandoning language"}$q$::jsonb, $q$A$q$, $q$The speaker applies the family's commitment to craft to writing rather than digging soil.$q$),
  ($q$Digging$q$, $q$Which tension is central to the speaker's attitude?$q$, $q${"A":"Hatred of his family against love of strangers","B":"Respect for inherited labour alongside a different vocation","C":"A wish to forget the past entirely","D":"Fear that crops will never grow"}$q$::jsonb, $q$B$q$, $q$He honours his relatives' work without claiming he must perform identical labour.$q$),
  ($q$Digging$q$, $q$Why does the poem move between the present speaker and remembered workers?$q$, $q${"A":"To hide the identity of the speaker","B":"To list dates of historical wars","C":"To connect personal choice with family inheritance","D":"To prove all work is physically identical"}$q$::jsonb, $q$C$q$, $q$The shifts in time place the writer's decision beside a tradition of skilled effort.$q$),
  ($q$Still I Rise$q$, $q$In Maya Angelou's Still I Rise, what does the recurring declaration of recovery emphasize?$q$, $q${"A":"Acceptance of defeat","B":"Fear of public speech","C":"Dependence on an oppressor's approval","D":"Resilience in the face of humiliation"}$q$::jsonb, $q$D$q$, $q$Repeated assertion presents the speaker as refusing to remain crushed by prejudice.$q$),
  ($q$Still I Rise$q$, $q$Why does the speaker address an unnamed hostile audience?$q$, $q${"A":"To confront the attitudes that try to diminish her","B":"To request permission to be confident","C":"To narrate a private weather report","D":"To explain a scientific formula"}$q$::jsonb, $q$A$q$, $q$Direct address challenges those who seek to shame or silence the speaker.$q$),
  ($q$Still I Rise$q$, $q$What does the poem's confident voice do to images of attempted oppression?$q$, $q${"A":"It approves of oppression","B":"It reverses their intended power over the speaker","C":"It shows the speaker has no memory","D":"It removes all reference to history"}$q$::jsonb, $q$B$q$, $q$The speaker answers degrading treatment with self-worth and determination.$q$),
  ($q$Still I Rise$q$, $q$Why does the poem connect personal survival with ancestral history?$q$, $q${"A":"To deny the past existed","B":"To describe a single family holiday","C":"To make resistance larger than one individual's experience","D":"To avoid the issue of identity"}$q$::jsonb, $q$C$q$, $q$The speaker's rise carries the memory and aspirations of earlier generations.$q$),
  ($q$Still I Rise$q$, $q$Which mood develops most strongly through the poem's repeated self-affirmation?$q$, $q${"A":"Resigned despair","B":"Detached neutrality","C":"Amused indifference","D":"Defiant hope"}$q$::jsonb, $q$D$q$, $q$Repetition strengthens the speaker's refusal to be diminished.$q$),
  ($q$The Telephone Call$q$, $q$In Fleur Adcock's The Telephone Call, what does the caller first lead the speaker to believe?$q$, $q${"A":"A huge cash prize has been won","B":"A friend has been arrested","C":"A journey has been cancelled","D":"A lost book has been found"}$q$::jsonb, $q$A$q$, $q$The caller presents the conversation as news of a substantial lottery win.$q$),
  ($q$The Telephone Call$q$, $q$Why is the eventual explanation of the prize ironic?$q$, $q${"A":"The speaker had bought many tickets","B":"The promised money turns out to be only an emotional experience","C":"The caller speaks in person","D":"The speaker expected no excitement"}$q$::jsonb, $q$B$q$, $q$The caller redefines a supposed financial reward as the excitement of believing in it.$q$),
  ($q$The Telephone Call$q$, $q$What does the caller's encouragement to describe feelings accomplish?$q$, $q${"A":"It pays the speaker's bills","B":"It identifies the caller's true name","C":"It prolongs and intensifies the speaker's false expectation","D":"It proves the speaker is a journalist"}$q$::jsonb, $q$C$q$, $q$The questioning builds emotional investment before the disappointing disclosure.$q$),
  ($q$The Telephone Call$q$, $q$How does conversational form help create the poem's effect?$q$, $q${"A":"It removes all suspense","B":"It reveals the ending first","C":"It turns the speaker into an omniscient narrator","D":"The exchange lets the reader experience the reversal with the speaker"}$q$::jsonb, $q$D$q$, $q$The dialogue unfolds the deception step by step before the final twist.$q$),
  ($q$The Telephone Call$q$, $q$Which criticism is most plausible in the poem's ending?$q$, $q${"A":"Manipulating someone's hopes can be cruel even if the caller calls it a gift","B":"A lottery always pays in cash","C":"Surprise is impossible in conversation","D":"Emotions have no value in any circumstance"}$q$::jsonb, $q$A$q$, $q$The speaker's excitement is engineered under a false promise, so the claimed reward is ethically troubling.$q$),
  ($q$The Stone$q$, $q$In Wilfrid Wilson Gibson's The Stone, why does the bereaved woman ask for a carved stone?$q$, $q${"A":"To sell it at market","B":"To mark her dead lover's grave","C":"To build a new house","D":"To reward a miner"}$q$::jsonb, $q$B$q$, $q$The memorial stone is requested after her lover dies in a quarry accident.$q$),
  ($q$The Stone$q$, $q$What does her inability to weep immediately suggest?$q$, $q${"A":"She did not care for him","B":"She already knows the future","C":"Her grief has left her numb","D":"She welcomes the accident"}$q$::jsonb, $q$C$q$, $q$Silence and stillness are signs of shock rather than absence of love.$q$),
  ($q$The Stone$q$, $q$Why is stone a powerful central image in this poem?$q$, $q${"A":"It proves the quarry is closed","B":"It is merely decorative","C":"It explains the narrator's job only","D":"It links the fatal accident, memorial and woman's emotional stillness"}$q$::jsonb, $q$D$q$, $q$The same material connects cause of death, act of remembrance and the survivor's numbness.$q$),
  ($q$The Stone$q$, $q$What is the effect of the narrator observing the woman's quiet vigil while he works?$q$, $q${"A":"It makes grief visible through sustained silence","B":"It proves she has forgotten the dead man","C":"It turns the poem into a comedy","D":"It resolves her loss at once"}$q$::jsonb, $q$A$q$, $q$Her wordless presence makes the depth and duration of her grief felt.$q$),
  ($q$The Stone$q$, $q$Which theme is developed by the contrast between cutting a memorial and facing an irreparable loss?$q$, $q${"A":"Political ambition","B":"The limits of material acts in answering grief","C":"Agricultural progress","D":"The rewards of gambling"}$q$::jsonb, $q$B$q$, $q$The carved stone honours the dead but cannot restore the lost life.$q$)
)
insert into public.questions (
  subject_id, exam_type, source, year, topic,
  prompt, options, correct_answer, explanation
)
select subject.id, subject.exam_type, $q$original$q$, null,
       candidate.topic, candidate.prompt, candidate.options,
       candidate.correct_answer, candidate.explanation
from candidates as candidate
cross join public.subjects as subject
where subject.id = '74d30747-d6fe-4ba3-aa2a-04a4c60577ff'::uuid
  and lower(subject.exam_type::text) = 'waec'
  and not exists (
    select 1 from public.questions as existing
    where existing.subject_id = subject.id
      and existing.prompt = candidate.prompt
  );

commit;
