-- Original, text-only WASSCE Government practice for the WAEC subject below.
-- Section B uses Nigeria for country-specific history and institutions.
-- Re-running this file skips prompts already present for this subject.
begin;

do $guard$
begin
  if not exists (
    select 1 from public.subjects
    where id = 'a628f321-1de0-4a78-baf4-a8aeca29f836'::uuid
      and lower(exam_type::text) = 'waec'
  ) then
    raise exception 'Expected WAEC Government subject is missing';
  end if;
end
$guard$;

with candidates (topic, prompt, options, correct_answer, explanation) as (
  values
  -- Meaning and scope of Government (6)
  ($q$Meaning and Scope of Government$q$, $q$A community has a territory, a permanent population and sovereign authority. Which term best describes the whole political entity?$q$, $q${"A":"A state","B":"A cabinet","C":"A political party","D":"A pressure group"}$q$::jsonb, $q$A$q$, $q$A state combines a population, defined territory, government and sovereignty; a cabinet is only part of its government.$q$),
  ($q$Meaning and Scope of Government$q$, $q$After an election, ministers change but the country's territory and population remain. What has changed?$q$, $q${"A":"The state itself","B":"The government in office","C":"The nation's borders","D":"Its sovereignty automatically"}$q$::jsonb, $q$B$q$, $q$Government is the group exercising state authority at a particular time; the state is more enduring.$q$),
  ($q$Meaning and Scope of Government$q$, $q$A council makes rules, enforces them and settles disputes in its community. Which meaning of government is emphasized?$q$, $q${"A":"Government as a school subject only","B":"Government as a building","C":"Government as the process of governing","D":"Government as a private company"}$q$::jsonb, $q$C$q$, $q$The example describes governing activities rather than merely officeholders or a field of study.$q$),
  ($q$Meaning and Scope of Government$q$, $q$Why does a student compare constitutions, elections and public institutions in Government class?$q$, $q${"A":"To replace every elected official","B":"To avoid public affairs","C":"To become a court automatically","D":"To understand political institutions and civic choices"}$q$::jsonb, $q$D$q$, $q$Government as an academic subject examines how authority and institutions work so citizens can make informed choices.$q$),
  ($q$Meaning and Scope of Government$q$, $q$A newly independent territory has citizens and institutions but another country controls its final foreign-policy decisions. Which state attribute is most clearly limited?$q$, $q${"A":"Sovereignty","B":"Population","C":"Territory","D":"Public administration"}$q$::jsonb, $q$A$q$, $q$Sovereignty is ultimate authority over internal and external affairs; external control limits that authority.$q$),
  ($q$Meaning and Scope of Government$q$, $q$A government funds schools and maintains roads using public revenue. Which broad function is illustrated?$q$, $q${"A":"Abolishing citizenship","B":"Providing public services","C":"Replacing all private choices","D":"Ending political participation"}$q$::jsonb, $q$B$q$, $q$Service provision is one function governments perform for the community.$q$),
  -- Basic concepts and principles (24)
  ($q$Basic Concepts and Principles of Government$q$, $q$A leader can command police officers but citizens no longer believe the leader has a right to rule. What is most directly lacking?$q$, $q${"A":"Coercive power","B":"Territory","C":"Legitimacy","D":"A written budget"}$q$::jsonb, $q$C$q$, $q$Legitimacy is acceptance of the right to exercise authority; coercive capacity can exist without it.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$An official's instructions are obeyed because the office legally empowers her to issue them. This is an example of what?$q$, $q${"A":"A private preference","B":"A natural resource","C":"A party manifesto","D":"Authority"}$q$::jsonb, $q$D$q$, $q$Authority is recognized, lawful power attached to an office or accepted rule.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$Two cultural communities identify with one shared political identity despite living in several states. Which concept concerns that shared identity?$q$, $q${"A":"Nation","B":"Cabinet","C":"Judiciary","D":"Civil service"}$q$::jsonb, $q$A$q$, $q$A nation refers to a people with a shared sense of identity; it need not coincide exactly with one state.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A child learns respect for elections through family discussions, school and news. What political process is occurring?$q$, $q${"A":"Judicial review","B":"Political socialization","C":"Privatization","D":"Delegated legislation"}$q$::jsonb, $q$B$q$, $q$Political socialization is the learning of political values and attitudes through social influences.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A public officer is punished under the same law that applies to ordinary citizens. Which principle is most directly upheld?$q$, $q${"A":"Absolute monarchy","B":"One-party rule","C":"Rule of law","D":"Military command"}$q$::jsonb, $q$C$q$, $q$Rule of law requires public officials and citizens alike to be subject to law.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$The legislature investigates executive spending and can demand an explanation. Which principle does this illustrate?$q$, $q${"A":"Unlimited executive power","B":"Fusion without accountability","C":"Suspension of elections","D":"Checks and balances"}$q$::jsonb, $q$D$q$, $q$Legislative scrutiny checks executive action and limits concentration of power.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A constitution gives elected representatives power to make laws while voters retain the ability to replace them. Which democratic idea is illustrated?$q$, $q${"A":"Representative government","B":"Hereditary rule","C":"Government by decree","D":"Judicial dictatorship"}$q$::jsonb, $q$A$q$, $q$Citizens govern indirectly through representatives who remain accountable through elections.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$An elected regional council receives legal authority to decide local service priorities instead of merely carrying out a minister's instructions. This is closest to what?$q$, $q${"A":"Mere field-office relocation","B":"Devolution of power","C":"A ministerial circular","D":"Temporary delegation only"}$q$::jsonb, $q$B$q$, $q$Devolution gives a lower-level institution meaningful discretion over its own decisions.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A ministry moves staff to provincial offices but headquarters retains every final decision. What has mainly occurred?$q$, $q${"A":"Full federalism","B":"Sovereign independence","C":"Deconcentration","D":"Judicial review"}$q$::jsonb, $q$C$q$, $q$Deconcentration disperses administrative work geographically without giving independent final authority.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$Parliament authorizes a minister to issue detailed safety rules within limits set by an Act. What are those rules an example of?$q$, $q${"A":"An amendment by referendum","B":"A court judgment","C":"An electoral manifesto","D":"Delegated legislation"}$q$::jsonb, $q$D$q$, $q$Delegated legislation is subordinate law made under authority granted by the legislature.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A person is detained without being told the charge or brought before a court. Which safeguard is most relevant?$q$, $q${"A":"The right to due process and personal liberty","B":"A higher import tariff","C":"A one-party constitution","D":"A ministerial budget"}$q$::jsonb, $q$A$q$, $q$Personal liberty and due process protect people against arbitrary detention.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A legislature passes a law but an independent court finds that it contradicts the constitution. What power is the court exercising?$q$, $q${"A":"Tax collection","B":"Judicial review","C":"Election campaigning","D":"Diplomatic recognition"}$q$::jsonb, $q$B$q$, $q$Judicial review tests official acts or laws against constitutional requirements.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$In a democracy, citizens organise a peaceful meeting to discuss a proposed law. What are they practising?$q$, $q${"A":"Military rule","B":"Royal succession","C":"Political participation","D":"Administrative secrecy"}$q$::jsonb, $q$C$q$, $q$Peaceful public discussion is a form of participation in political decisions.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A small group of wealthy families monopolizes major decisions and excludes most citizens. Which label best fits?$q$, $q${"A":"Direct democracy","B":"Universal franchise","C":"Federalism","D":"Oligarchy"}$q$::jsonb, $q$D$q$, $q$Oligarchy is rule by a small group rather than broad popular participation.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$Public agencies can act only within powers given by a higher law, and courts can enforce that limit. What principle is illustrated?$q$, $q${"A":"Constitutionalism","B":"Unlimited sovereignty of an official","C":"Rule by personal favour","D":"Hereditary office"}$q$::jsonb, $q$A$q$, $q$Constitutionalism limits public authority through enforceable constitutional rules.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A society expects officials to resign when they abuse public resources. Such shared expectations form part of its what?$q$, $q${"A":"Territorial boundary","B":"Political culture","C":"Court registry","D":"Military arsenal"}$q$::jsonb, $q$B$q$, $q$Political culture consists of shared attitudes and expectations about politics and authority.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A proposal would abolish independent newspapers and permit only one official political ideology. Which system does this resemble most?$q$, $q${"A":"Pluralist democracy","B":"Loose confederation","C":"Totalitarian rule","D":"Judicial federalism"}$q$::jsonb, $q$C$q$, $q$Totalitarian rule seeks extensive control over political and social life and suppresses alternatives.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$Neighbouring households manage a shared well and divide its upkeep by community agreement. Which idea is closest?$q$, $q${"A":"Absolute monarchy","B":"Private dictatorship","C":"Foreign occupation","D":"Communalism"}$q$::jsonb, $q$D$q$, $q$Communalism stresses collective responsibility and use of shared community resources.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A political programme would leave most businesses privately owned while relying on competition and private investment. Which economic ideology is closest?$q$, $q${"A":"Capitalism","B":"Feudalism","C":"Communism","D":"Military rule"}$q$::jsonb, $q$A$q$, $q$Capitalism emphasizes private ownership and market exchange.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A policy expands public ownership of key industries to reduce economic inequality. Which ideology is most closely associated with it?$q$, $q${"A":"Feudalism","B":"Socialism","C":"Aristocracy","D":"Absolutism"}$q$::jsonb, $q$B$q$, $q$Socialism commonly supports social or public ownership of major productive resources.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A ruler claims final power comes from inheritance and cannot be questioned by the courts. Which democratic safeguard is most directly threatened?$q$, $q${"A":"A national anthem","B":"A census","C":"Legal limits on power","D":"Postal service"}$q$::jsonb, $q$C$q$, $q$Accountable constitutional government requires rulers to obey enforceable legal limits.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A bill of rights protects criticism of government even when leaders dislike it. Which value does this protect?$q$, $q${"A":"Forced unanimity","B":"Arbitrary detention","C":"Unelected succession","D":"Freedom of expression"}$q$::jsonb, $q$D$q$, $q$Freedom of expression protects lawful political criticism and debate.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$A president appoints judges, but a separate body controls judicial discipline and judges have secure tenure. What is the main purpose?$q$, $q${"A":"Judicial independence","B":"To remove all laws","C":"To make judges political candidates","D":"To abolish appeals"}$q$::jsonb, $q$A$q$, $q$Security of tenure and independent discipline reduce pressure on judges from the executive.$q$),
  ($q$Basic Concepts and Principles of Government$q$, $q$The majority wins an election, yet the minority keeps legal rights to campaign for the next one. What feature of democracy is shown?$q$, $q${"A":"Permanent one-party rule","B":"Protection of opposition and minority rights","C":"Rule solely by armed force","D":"Ban on disagreement"}$q$::jsonb, $q$B$q$, $q$Democracy combines majority decision-making with safeguards for opposition and minority rights.$q$),
  -- Constitutions (10)
  ($q$Constitutions$q$, $q$A constitution states who may make laws and how leaders are chosen. What is its main institutional role?$q$, $q${"A":"To predict every election result","B":"To replace ordinary laws entirely","C":"To organize and limit public authority","D":"To set every market price"}$q$::jsonb, $q$C$q$, $q$A constitution establishes state institutions, distributes power and places limits on its exercise.$q$),
  ($q$Constitutions$q$, $q$A proposed constitutional amendment needs a supermajority and approval by regional legislatures. The constitution is relatively what?$q$, $q${"A":"Unwritten","B":"Temporary","C":"Flexible","D":"Rigid"}$q$::jsonb, $q$D$q$, $q$A rigid constitution requires a more demanding amendment procedure than an ordinary law.$q$),
  ($q$Constitutions$q$, $q$Ordinary parliamentary votes can amend most constitutional rules. This constitution is relatively what?$q$, $q${"A":"Flexible","B":"Federal by definition","C":"Unenforceable","D":"Military"}$q$::jsonb, $q$A$q$, $q$A flexible constitution can be changed through procedures close to those for ordinary legislation.$q$),
  ($q$Constitutions$q$, $q$A country's constitutional rules are found partly in statutes, judgments and long-standing conventions rather than one document. How is it usually described?$q$, $q${"A":"Having no constitution","B":"Uncodified or unwritten","C":"Automatically federal","D":"Automatically republican"}$q$::jsonb, $q$B$q$, $q$An uncodified constitution has rules spread across several sources, not an absence of rules.$q$),
  ($q$Constitutions$q$, $q$A court settles a dispute by applying a constitutional rule established in an earlier judgment. What source is it using?$q$, $q${"A":"A campaign poster","B":"An opinion poll","C":"Judicial precedent","D":"A party slogan"}$q$::jsonb, $q$C$q$, $q$Past judicial decisions can be a source of constitutional rules or interpretation.$q$),
  ($q$Constitutions$q$, $q$Why does a federal constitution normally specify the powers of central and regional governments?$q$, $q${"A":"To end all elections","B":"To make courts unnecessary","C":"To eliminate local identities","D":"To reduce disputes over jurisdiction"}$q$::jsonb, $q$D$q$, $q$An explicit division clarifies which level may act in different policy areas.$q$),
  ($q$Constitutions$q$, $q$A minister issues an order that conflicts with the constitution. In a system of constitutional supremacy, what follows?$q$, $q${"A":"The order can be set aside","B":"The constitution becomes void","C":"The minister can amend the constitution alone","D":"The conflict is irrelevant"}$q$::jsonb, $q$A$q$, $q$Constitutional supremacy makes inconsistent lower-level action invalid to the extent of the conflict.$q$),
  ($q$Constitutions$q$, $q$A document grants rights but provides no independent way to challenge official violations. What important support for those rights is missing?$q$, $q${"A":"A larger cabinet","B":"Effective enforcement mechanisms","C":"More political slogans","D":"A change of flag"}$q$::jsonb, $q$B$q$, $q$Rights need accessible remedies and institutions that can enforce them.$q$),
  ($q$Constitutions$q$, $q$Which change is most likely to require a constitutional amendment rather than an ordinary administrative instruction?$q$, $q${"A":"Moving a ministry's filing room","B":"Changing office stationery","C":"Altering the constitutionally fixed length of a presidential term","D":"Scheduling a staff meeting"}$q$::jsonb, $q$C$q$, $q$A term fixed by the constitution can be changed only by the prescribed amendment process.$q$),
  ($q$Constitutions$q$, $q$A convention says a minister should resign after losing legislative confidence, although the rule is not in one statute. What does this show?$q$, $q${"A":"Only written statutes matter","B":"Conventions are court sentences","C":"Elections are unnecessary","D":"Political conventions can shape constitutional practice"}$q$::jsonb, $q$D$q$, $q$Established political conventions can guide institutions even when not codified in one statute.$q$),
  -- Organs of Government (10 of 16)
  ($q$Organs of Government$q$, $q$A bill is debated, amended and passed by elected lawmakers. Which organ performs this core task?$q$, $q${"A":"Legislature","B":"Judiciary","C":"Civil service commission","D":"Police command"}$q$::jsonb, $q$A$q$, $q$Lawmaking is a central function of the legislature.$q$),
  ($q$Organs of Government$q$, $q$A ministry turns a lawful education budget into school programmes. Which organ is mainly responsible for implementation?$q$, $q${"A":"The opposition party","B":"Executive","C":"Appellate court","D":"Electoral commission"}$q$::jsonb, $q$B$q$, $q$The executive administers laws and implements approved policies.$q$),
  ($q$Organs of Government$q$, $q$Two citizens dispute the meaning of a statute and seek a binding legal decision. Which organ should resolve it?$q$, $q${"A":"The cabinet alone","B":"A party caucus","C":"Judiciary","D":"A pressure group"}$q$::jsonb, $q$C$q$, $q$Courts interpret and apply law when deciding disputes.$q$),
  ($q$Organs of Government$q$, $q$Why are judges usually protected from removal merely for an unpopular lawful judgment?$q$, $q${"A":"To stop all appeals","B":"To let judges make budgets","C":"To give judges unlimited power","D":"To reduce political intimidation"}$q$::jsonb, $q$D$q$, $q$Security of tenure helps judges decide cases without fear of retaliation.$q$),
  ($q$Organs of Government$q$, $q$The legislature refuses to approve funds for an unlawful executive programme. Which power is it using?$q$, $q${"A":"Control of public expenditure","B":"Judicial sentencing","C":"Command of the armed forces","D":"Diplomatic immunity"}$q$::jsonb, $q$A$q$, $q$Legislative budget approval is a check on executive spending.$q$),
  ($q$Organs of Government$q$, $q$A president can veto a bill, but lawmakers can override the veto under set conditions. What relationship is illustrated?$q$, $q${"A":"Abolition of legislature","B":"Checks between branches","C":"Complete judicial control","D":"Rule by civil servants"}$q$::jsonb, $q$B$q$, $q$Veto and override powers make branches check each other's decisions.$q$),
  ($q$Organs of Government$q$, $q$A lower court's decision is reviewed by a higher court for an error of law. What judicial function is shown?$q$, $q${"A":"Election management","B":"Tax assessment","C":"Hearing an appeal","D":"Writing a party manifesto"}$q$::jsonb, $q$C$q$, $q$An appellate court reviews lower-court decisions under the applicable appeal rules.$q$),
  ($q$Organs of Government$q$, $q$A minister proposes a policy, but the legislature must enact a law before citizens can be bound by it. What does this show?$q$, $q${"A":"Ministers replace courts","B":"Policies never need laws","C":"Legislatures administer ministries","D":"Executive proposals do not automatically become law"}$q$::jsonb, $q$D$q$, $q$Where legislation is required, the legislature must authorize the binding rule.$q$),
  ($q$Organs of Government$q$, $q$An executive officer refuses to enforce a final court order because it is politically inconvenient. Which principle is threatened?$q$, $q${"A":"Respect for judicial decisions and the rule of law","B":"Legislative recess","C":"Party registration","D":"Population counting"}$q$::jsonb, $q$A$q$, $q$Final lawful court orders must be obeyed for judicial authority and rule of law to have effect.$q$),
  ($q$Organs of Government$q$, $q$A legislature summons a minister to answer questions about a public project. What is this an example of?$q$, $q${"A":"Court sentencing","B":"Legislative oversight","C":"Civil-service recruitment","D":"Foreign recognition"}$q$::jsonb, $q$B$q$, $q$Questioning ministers is a method of legislative oversight of the executive.$q$),
  ($q$Organs of Government$q$, $q$Which institution is best placed to determine whether a defendant received a fair hearing under the law?$q$, $q${"A":"The ruling party","B":"A campaign committee","C":"An independent court","D":"The treasury"}$q$::jsonb, $q$C$q$, $q$Courts determine legal rights and procedural fairness in cases brought before them.$q$),
  ($q$Organs of Government$q$, $q$A cabinet selects a proposed national policy and directs ministries to carry it out after lawful approval. Cabinet belongs to which organ?$q$, $q${"A":"Legislature","B":"Judiciary","C":"Electoral commission","D":"Executive"}$q$::jsonb, $q$D$q$, $q$Cabinet ministers direct executive policy and administration.$q$),
  ($q$Organs of Government$q$, $q$A two-chamber parliament requires a bill to pass through both chambers. What is this legislative arrangement called?$q$, $q${"A":"Bicameralism","B":"Unicameralism","C":"Confederation","D":"Judicial review"}$q$::jsonb, $q$A$q$, $q$A bicameral legislature has two chambers; a unicameral legislature has one.$q$),
  ($q$Organs of Government$q$, $q$A judge is asked by a minister to decide a pending case in the government's favour. What should judicial independence require?$q$, $q${"A":"Obeying the minister","B":"Deciding on evidence and law without improper pressure","C":"Joining the minister's party","D":"Refusing all cases involving government"}$q$::jsonb, $q$B$q$, $q$Independent adjudication applies law and evidence without political interference.$q$),
  ($q$Organs of Government$q$, $q$Parliament changes the wording of a proposed Act before voting on it. Which legislative function is involved?$q$, $q${"A":"Diplomatic recognition","B":"Court enforcement","C":"Scrutiny and amendment of bills","D":"Police recruitment"}$q$::jsonb, $q$C$q$, $q$Debating and amending bills improves or changes proposed legislation.$q$),
  ($q$Organs of Government$q$, $q$A legislature can make laws, but it cannot lawfully ignore constitutional limits. What limits its lawmaking power?$q$, $q${"A":"Only newspaper headlines","B":"Only party slogans","C":"The weather","D":"The constitution"}$q$::jsonb, $q$D$q$, $q$In a constitutional system, legislation must comply with superior constitutional rules.$q$),
  -- State structures and forms of government (16)
  ($q$State Structures and Forms of Government$q$, $q$One national parliament can change the powers of local councils by ordinary law. Which state structure is most likely?$q$, $q${"A":"Unitary","B":"Federal","C":"Confederal","D":"A federation of sovereign states"}$q$::jsonb, $q$A$q$, $q$In a unitary state, local authorities derive their powers from the central state.$q$),
  ($q$State Structures and Forms of Government$q$, $q$Central and state governments each have powers protected by a written constitution. Which structure fits best?$q$, $q${"A":"A unitary state","B":"A federation","C":"A private association","D":"A military council"}$q$::jsonb, $q$B$q$, $q$Federalism constitutionally divides authority between national and subnational governments.$q$),
  ($q$State Structures and Forms of Government$q$, $q$Independent countries create a joint body for limited common tasks but keep most sovereign authority. What have they formed?$q$, $q${"A":"A unitary state","B":"A single municipality","C":"A confederation","D":"A cabinet government"}$q$::jsonb, $q$C$q$, $q$A confederation is a loose union of largely sovereign member states.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A head of government must retain the confidence of parliament to stay in office. Which system is described?$q$, $q${"A":"Presidential","B":"Absolute monarchy","C":"Military","D":"Parliamentary"}$q$::jsonb, $q$D$q$, $q$In a parliamentary system, the executive's survival depends on legislative confidence.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A president is elected for a fixed term and ministers are not legislators by virtue of being ministers. Which system is closest?$q$, $q${"A":"Presidential","B":"Parliamentary","C":"Confederal","D":"Feudal"}$q$::jsonb, $q$A$q$, $q$A presidential system separates the executive from the legislature and ordinarily uses a fixed executive term.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A ceremonial monarch is head of state while an elected prime minister directs government. Which combination is this?$q$, $q${"A":"Absolute monarchy with no cabinet","B":"Constitutional monarchy with parliamentary government","C":"Republic without an executive","D":"Military federation"}$q$::jsonb, $q$B$q$, $q$A constitutional monarch may serve as ceremonial head of state while a prime minister governs.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A country's head of state gains office through an electoral process rather than hereditary succession. What broad form is it?$q$, $q${"A":"Monarchy","B":"Feudalism","C":"Republic","D":"Confederation"}$q$::jsonb, $q$C$q$, $q$A republic has a non-hereditary head of state; selection methods can vary.$q$),
  ($q$State Structures and Forms of Government$q$, $q$Two states in a federation disagree over a constitutionally shared tax. Which institution should interpret the division of powers?$q$, $q${"A":"A party treasurer","B":"A newspaper editor","C":"A private club","D":"A competent court"}$q$::jsonb, $q$D$q$, $q$A court can resolve constitutional disputes between levels of government.$q$),
  ($q$State Structures and Forms of Government$q$, $q$Why might federalism appeal to a country with large regions and diverse communities?$q$, $q${"A":"It permits regional self-government within one state","B":"It removes the need for national coordination","C":"It guarantees identical local customs","D":"It abolishes constitutional courts"}$q$::jsonb, $q$A$q$, $q$Federalism can accommodate local differences while maintaining national institutions.$q$),
  ($q$State Structures and Forms of Government$q$, $q$Why can a unitary system sometimes coordinate nationwide policy more quickly?$q$, $q${"A":"It has no citizens","B":"Major authority is concentrated at the centre","C":"It has no local offices","D":"It cannot be democratic"}$q$::jsonb, $q$B$q$, $q$Centralized decision-making can reduce negotiation among autonomous levels, though speed is not guaranteed.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A prime minister loses a vote of confidence and resigns. Which idea best explains this outcome?$q$, $q${"A":"Judicial tenure","B":"Presidential fixed term","C":"Collective accountability to parliament","D":"Confederal sovereignty"}$q$::jsonb, $q$C$q$, $q$Parliamentary executives remain in office only while they can command legislative confidence.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A president has a fixed term but must still obey courts and the constitution. Which statement follows?$q$, $q${"A":"A fixed term removes legal accountability","B":"Courts cannot review executive action","C":"The president may rule without laws","D":"Presidential government can still be constitutionally limited"}$q$::jsonb, $q$D$q$, $q$A fixed executive term does not place the president above constitutional law.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A central government delegates waste collection to local offices but may revoke the delegation. Does this alone make the country federal?$q$, $q${"A":"No; revocable local delegation is not a protected division of sovereignty","B":"Yes; any local office creates a federation","C":"Yes; waste collection is always a federal power","D":"No; federations cannot have local services"}$q$::jsonb, $q$A$q$, $q$Federalism requires a constitutionally protected division of authority, not merely administrative delegation.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A monarch inherits a throne but has no power to reject laws made by elected representatives. Which distinction matters here?$q$, $q${"A":"All monarchies are absolute","B":"Monarchy can be constitutional rather than absolute","C":"Republic and monarchy mean the same thing","D":"Parliament cannot exist with a monarch"}$q$::jsonb, $q$B$q$, $q$A constitutional monarchy limits the monarch's governing authority.$q$),
  ($q$State Structures and Forms of Government$q$, $q$A loose union struggles to collect contributions from member states for a joint project. Which structural weakness may explain this?$q$, $q${"A":"Too much direct central taxation","B":"A national court always controls local budgets","C":"The confederal centre depends heavily on member cooperation","D":"All members have lost sovereignty"}$q$::jsonb, $q$C$q$, $q$Confederal institutions often depend on member states for resources and compliance.$q$),
  ($q$State Structures and Forms of Government$q$, $q$Which feature distinguishes a parliamentary cabinet from a presidential cabinet most clearly?$q$, $q${"A":"Parliamentary cabinets never make policy","B":"Presidential cabinets always make statutes","C":"Parliamentary cabinets are courts","D":"A parliamentary cabinet is politically answerable to parliament"}$q$::jsonb, $q$D$q$, $q$Cabinet responsibility to parliament is central to parliamentary government.$q$),
  -- Citizenship (8)
  ($q$Citizenship$q$, $q$A child acquires citizenship because a parent is a citizen under the country's law. Which route is this?$q$, $q${"A":"Citizenship by descent","B":"Citizenship by election","C":"Diplomatic immunity","D":"Political asylum"}$q$::jsonb, $q$A$q$, $q$Citizenship by descent derives from the legal citizenship of a parent.$q$),
  ($q$Citizenship$q$, $q$A foreign resident meets statutory conditions and is granted citizenship after applying. Which route is this?$q$, $q${"A":"Hereditary office","B":"Naturalization","C":"Judicial review","D":"Devolution"}$q$::jsonb, $q$B$q$, $q$Naturalization is the legal grant of citizenship to an eligible non-citizen.$q$),
  ($q$Citizenship$q$, $q$A citizen votes and also pays lawful taxes. What do these actions illustrate together?$q$, $q${"A":"Only legal immunity","B":"Only cabinet membership","C":"Political rights and civic duties","D":"Loss of citizenship"}$q$::jsonb, $q$C$q$, $q$Voting is a political right, while tax payment is a civic obligation.$q$),
  ($q$Citizenship$q$, $q$A person claims an official has violated a protected right. Which response best safeguards that right?$q$, $q${"A":"A ban on legal representation","B":"Secret punishment","C":"Ignoring the complaint","D":"Access to an independent court"}$q$::jsonb, $q$D$q$, $q$Independent judicial remedies allow citizens to challenge unlawful official conduct.$q$),
  ($q$Citizenship$q$, $q$Why does freedom of association matter to citizens in a democracy?$q$, $q${"A":"It allows them to organize peacefully around shared interests","B":"It guarantees every group a government post","C":"It abolishes public duties","D":"It prevents all disagreement"}$q$::jsonb, $q$A$q$, $q$Association lets people form lawful groups and participate collectively in public life.$q$),
  ($q$Citizenship$q$, $q$A person refuses to obey a valid court order while demanding that others respect her rights. What civic duty is she neglecting?$q$, $q${"A":"Membership of a political party","B":"Obedience to lawful decisions","C":"Ownership of property","D":"Eligibility to vote"}$q$::jsonb, $q$B$q$, $q$Citizens have a duty to obey valid laws and court orders, alongside enjoying rights.$q$),
  ($q$Citizenship$q$, $q$A government publishes clear procedures for reviewing the denial of citizenship. Which value does this most support?$q$, $q${"A":"Arbitrary rule","B":"Secret enforcement","C":"Fair administrative process","D":"Hereditary privilege"}$q$::jsonb, $q$C$q$, $q$Clear review procedures help applicants contest errors and support due process.$q$),
  ($q$Citizenship$q$, $q$A lawful protest is banned only because its message criticizes officials. Which citizen right is most directly threatened?$q$, $q${"A":"A right to appoint ministers","B":"A right to ignore taxes","C":"A right to unlimited public funds","D":"Freedom of expression and assembly"}$q$::jsonb, $q$D$q$, $q$Peaceful criticism and assembly are protected forms of civic participation.$q$),
  -- Political parties and party systems (10)
  ($q$Political Parties and Party Systems$q$, $q$A group selects candidates and presents a policy programme to win public office. What is it?$q$, $q${"A":"Political party","B":"Court registry","C":"Civil service commission","D":"Independent newspaper"}$q$::jsonb, $q$A$q$, $q$Political parties contest elections to exercise governing power through candidates and programmes.$q$),
  ($q$Political Parties and Party Systems$q$, $q$Two large parties alternate in government while smaller parties rarely win seats. Which party system is most closely described?$q$, $q${"A":"No-party system","B":"Two-party-dominant system","C":"One-party monopoly","D":"Military government"}$q$::jsonb, $q$B$q$, $q$A two-party-dominant system has two parties that usually form governments.$q$),
  ($q$Political Parties and Party Systems$q$, $q$Several parties must negotiate a coalition because none wins a legislative majority. What party system is most likely?$q$, $q${"A":"A ban on all parties","B":"A hereditary monarchy","C":"Multiparty system","D":"A court system"}$q$::jsonb, $q$C$q$, $q$Coalition bargaining is common when several competitive parties share seats.$q$),
  ($q$Political Parties and Party Systems$q$, $q$A party's local branches collect community complaints and send them to national leaders. What party function is illustrated?$q$, $q${"A":"Judicial sentencing","B":"Currency issuance","C":"Border policing","D":"Interest aggregation"}$q$::jsonb, $q$D$q$, $q$Parties gather and combine citizens' demands into political programmes.$q$),
  ($q$Political Parties and Party Systems$q$, $q$An opposition party questions spending and offers an alternative budget. What democratic role is it playing?$q$, $q${"A":"Holding government accountable","B":"Replacing the courts","C":"Ending electoral choice","D":"Appointing all civil servants"}$q$::jsonb, $q$A$q$, $q$Opposition parties scrutinize those in office and present alternative policies.$q$),
  ($q$Political Parties and Party Systems$q$, $q$A party nominates candidates through a transparent vote by members instead of a leader's private choice. What principle is strengthened?$q$, $q${"A":"Military hierarchy","B":"Internal party democracy","C":"Hereditary succession","D":"Judicial immunity"}$q$::jsonb, $q$B$q$, $q$Member participation in candidate selection strengthens internal democracy.$q$),
  ($q$Political Parties and Party Systems$q$, $q$One party alone may legally contest elections, although citizens can vote. What important feature of competitive democracy is missing?$q$, $q${"A":"A ballot box","B":"A fixed polling date","C":"Meaningful party choice","D":"A national flag"}$q$::jsonb, $q$C$q$, $q$Without competing parties, voters cannot choose among alternative governing programmes.$q$),
  ($q$Political Parties and Party Systems$q$, $q$A party recruits new activists and teaches them how to campaign lawfully. Which function is this?$q$, $q${"A":"Court adjudication","B":"Tax assessment","C":"Trade regulation","D":"Political recruitment and education"}$q$::jsonb, $q$D$q$, $q$Parties bring people into political life and help them learn participation skills.$q$),
  ($q$Political Parties and Party Systems$q$, $q$Why might coalition parties agree on a common programme before taking office?$q$, $q${"A":"To coordinate policy despite different priorities","B":"To make elections unnecessary","C":"To transfer sovereignty abroad","D":"To avoid all legislative votes"}$q$::jsonb, $q$A$q$, $q$A coalition agreement helps partners coordinate decisions and manage disagreements.$q$),
  ($q$Political Parties and Party Systems$q$, $q$Voters cannot tell how a party finances its campaign. Which reform would most directly address this concern?$q$, $q${"A":"Longer party slogans","B":"Transparent funding disclosure","C":"Fewer public debates","D":"Secret candidate lists"}$q$::jsonb, $q$B$q$, $q$Funding disclosure lets voters and regulators examine possible undue influence.$q$),
  -- Pressure groups, public opinion and mass media (10)
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$Teachers lobby legislators about school funding but do not field candidates. What are they acting as?$q$, $q${"A":"A ruling party","B":"An electoral commission","C":"A pressure group","D":"A court"}$q$::jsonb, $q$C$q$, $q$A pressure group seeks to influence policy without primarily seeking government office.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$A farmers' association sends research to lawmakers before a vote. Which method of influence is it using?$q$, $q${"A":"Judicial sentencing","B":"Armed rule","C":"Vote counting","D":"Lobbying with evidence"}$q$::jsonb, $q$D$q$, $q$Providing evidence directly to decision-makers is a form of lobbying.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$A radio debate helps citizens compare several views on a tax proposal. Which media role is illustrated?$q$, $q${"A":"Providing a forum for public discussion","B":"Replacing parliament","C":"Appointing judges","D":"Writing the constitution alone"}$q$::jsonb, $q$A$q$, $q$Mass media can inform citizens and host debate on public issues.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$A poll surveys only members of one political party but claims to represent the whole country. What is its main flaw?$q$, $q${"A":"Too many questions","B":"A biased sample","C":"Too much anonymity","D":"No possible response categories"}$q$::jsonb, $q$B$q$, $q$A party-only sample is not representative of all citizens, so the result may misstate national opinion.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$Many citizens express similar views about a proposed law in surveys, meetings and letters. What is being observed?$q$, $q${"A":"A court precedent","B":"A cabinet appointment","C":"Public opinion","D":"A constitutional amendment"}$q$::jsonb, $q$C$q$, $q$Public opinion is the collective pattern of views held by members of the public on an issue.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$An editor checks a claim against documents before publishing it. Why is this important for democracy?$q$, $q${"A":"It removes all political disagreement","B":"It lets editors replace elections","C":"It gives officials immunity","D":"Accurate information supports informed participation"}$q$::jsonb, $q$D$q$, $q$Citizens need reliable information to judge policies and leaders.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$A health association argues for safer water in court and through public campaigns. Which statement is correct?$q$, $q${"A":"Pressure groups may use several lawful channels","B":"Only political parties may influence policy","C":"Court action always replaces legislation","D":"Campaigning cancels citizenship"}$q$::jsonb, $q$A$q$, $q$Groups may combine litigation, advocacy and public education to pursue policy change.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$A newspaper reports only the government's position while hiding relevant opposing evidence. What democratic risk increases?$q$, $q${"A":"Better accountability","B":"Poorly informed public judgment","C":"More independent scrutiny","D":"Automatic judicial review"}$q$::jsonb, $q$B$q$, $q$One-sided coverage can deny citizens information needed to assess decisions.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$A poll's wording suggests that only irresponsible people oppose a policy. Why may its result be unreliable?$q$, $q${"A":"The sample is necessarily too large","B":"The issue has no public interest","C":"Leading wording can influence responses","D":"All respondents must be civil servants"}$q$::jsonb, $q$C$q$, $q$Leading questions can bias answers by pushing respondents toward a preferred view.$q$),
  ($q$Pressure Groups, Public Opinion and Mass Media$q$, $q$Two groups disagree about a bill and both present evidence peacefully. What does this illustrate?$q$, $q${"A":"An end to participation","B":"A ban on organized interests","C":"The absence of policy debate","D":"Pluralism in public life"}$q$::jsonb, $q$D$q$, $q$Pluralism permits different organized interests to participate and compete peacefully.$q$),
  -- Elections and electoral management (12)
  ($q$Elections and Electoral Management$q$, $q$Every adult citizen may vote unless a narrow lawful disqualification applies. Which principle is most closely reflected?$q$, $q${"A":"Universal adult suffrage","B":"Restricted property franchise","C":"Hereditary office","D":"A closed primary"}$q$::jsonb, $q$A$q$, $q$Universal adult suffrage extends the vote broadly to eligible adults rather than a narrow social group.$q$),
  ($q$Elections and Electoral Management$q$, $q$A constituency elects the candidate with the most votes even though that candidate receives less than half. Which system is being used?$q$, $q${"A":"Proportional representation","B":"First-past-the-post","C":"A two-round majority vote","D":"Indirect appointment"}$q$::jsonb, $q$B$q$, $q$First-past-the-post chooses the highest vote-getter in a constituency without requiring an absolute majority.$q$),
  ($q$Elections and Electoral Management$q$, $q$Seats are allocated to parties broadly in line with each party's share of the vote. Which electoral principle is this?$q$, $q${"A":"Hereditary selection","B":"Appointment by cabinet","C":"Proportional representation","D":"Military nomination"}$q$::jsonb, $q$C$q$, $q$Proportional representation aims to align seat shares more closely with vote shares.$q$),
  ($q$Elections and Electoral Management$q$, $q$A poll worker gives voters a private space to mark their ballots. Which safeguard does this support?$q$, $q${"A":"Public identification of every choice","B":"Vote buying","C":"Multiple voting","D":"Secret ballot"}$q$::jsonb, $q$D$q$, $q$A secret ballot protects voters from intimidation or pressure over their choices.$q$),
  ($q$Elections and Electoral Management$q$, $q$A voter roll contains the same person twice. Which electoral body's task is most directly relevant?$q$, $q${"A":"Maintaining an accurate register of voters","B":"Writing court judgments","C":"Making foreign treaties","D":"Appointing ministers"}$q$::jsonb, $q$A$q$, $q$The electoral management body must maintain a reliable voter register to prevent duplicate voting.$q$),
  ($q$Elections and Electoral Management$q$, $q$A candidate offers cash only to people who promise to vote for her. Which practice threatens a free election?$q$, $q${"A":"Public debate","B":"Vote buying","C":"Ballot secrecy","D":"Independent observation"}$q$::jsonb, $q$B$q$, $q$Payment tied to voting preference improperly influences electoral choice.$q$),
  ($q$Elections and Electoral Management$q$, $q$An electoral agency publishes polling locations and procedures well before voting day. What does this most directly promote?$q$, $q${"A":"A ban on observers","B":"An end to voter registration","C":"Informed voter access","D":"Permanent rule by officials"}$q$::jsonb, $q$C$q$, $q$Clear advance information helps eligible voters know where and how to vote.$q$),
  ($q$Elections and Electoral Management$q$, $q$A government redraws constituencies solely to give its supporters more seats than their votes justify. What problem is this?$q$, $q${"A":"A secret ballot","B":"A public referendum","C":"A fair boundary review","D":"Gerrymandering"}$q$::jsonb, $q$D$q$, $q$Gerrymandering manipulates electoral boundaries for partisan advantage.$q$),
  ($q$Elections and Electoral Management$q$, $q$A voter chooses representatives who later select a president. What type of presidential election is this?$q$, $q${"A":"Indirect election","B":"Direct universal vote for president","C":"Hereditary succession","D":"Random selection"}$q$::jsonb, $q$A$q$, $q$In an indirect election, voters choose intermediaries who then choose the officeholder.$q$),
  ($q$Elections and Electoral Management$q$, $q$An electoral commission's chair can be dismissed at will by a candidate in government. What risk does this create?$q$, $q${"A":"Guaranteed impartiality","B":"Political interference in election management","C":"Automatic voter turnout","D":"A stronger secret ballot"}$q$::jsonb, $q$B$q$, $q$Insecure tenure can make election officials vulnerable to pressure from incumbents.$q$),
  ($q$Elections and Electoral Management$q$, $q$A candidate disputes a declared result using evidence of invalid ballots. Which peaceful channel should resolve the dispute?$q$, $q${"A":"Private violence","B":"An unverified rumour","C":"The lawful election-petition process","D":"A party slogan"}$q$::jsonb, $q$C$q$, $q$Election petitions provide a legal process for reviewing disputed results.$q$),
  ($q$Elections and Electoral Management$q$, $q$Why is an independent count observed by party agents useful?$q$, $q${"A":"It removes the need for ballots","B":"It guarantees every candidate wins","C":"It makes registration unnecessary","D":"It improves transparency and trust"}$q$::jsonb, $q$D$q$, $q$Independent observation and transparent counting help detect errors and build confidence.$q$),
  -- Public and civil service administration (10)
  ($q$Public and Civil Service Administration$q$, $q$Career officials remain after a new government takes office and continue implementing lawful policies. Which civil-service feature is shown?$q$, $q${"A":"Continuity","B":"Hereditary rule","C":"Party ownership","D":"Judicial supremacy"}$q$::jsonb, $q$A$q$, $q$The permanent civil service provides continuity across changes of political leadership.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A civil servant must give professional advice to whichever elected government is in office. Which norm is most relevant?$q$, $q${"A":"Partisan campaigning at work","B":"Political neutrality in official duties","C":"Private ownership of the ministry","D":"Refusal to implement lawful policy"}$q$::jsonb, $q$B$q$, $q$Neutral service supports lawful governments without using official duties for party campaigning.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A commission recruits staff through open competition rather than personal favour. What is its main purpose?$q$, $q${"A":"To count election votes","B":"To decide criminal appeals","C":"To support merit-based public appointments","D":"To set foreign exchange rates"}$q$::jsonb, $q$C$q$, $q$Civil-service commissions can protect merit and fairness in recruitment and discipline.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A state-owned bus company sells fares but also serves routes private firms avoid. What is it?$q$, $q${"A":"A political party","B":"A court","C":"A private household","D":"A public corporation"}$q$::jsonb, $q$D$q$, $q$A public corporation is a state-owned enterprise established to provide goods or services.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A public enterprise stays state-owned but is told to cover more of its costs from sales. What policy is this?$q$, $q${"A":"Commercialization","B":"Privatization","C":"Nationalization of a private firm","D":"Judicial review"}$q$::jsonb, $q$A$q$, $q$Commercialization applies business principles without necessarily transferring ownership.$q$),
  ($q$Public and Civil Service Administration$q$, $q$The state sells its shares in a public enterprise to private investors. What is this called?$q$, $q${"A":"Decentralized filing","B":"Privatization","C":"Civil-service tenure","D":"Electoral registration"}$q$::jsonb, $q$B$q$, $q$Privatization transfers ownership from the public to the private sector.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A local council repairs community drains and manages a nearby market. Why is local government suited to these tasks?$q$, $q${"A":"It makes national treaties","B":"It commands every court","C":"It is close to local needs","D":"It replaces all ministries"}$q$::jsonb, $q$C$q$, $q$Local authorities can respond to services and problems experienced directly by residents.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A local government receives a share of national revenue in addition to locally collected fees. What are these two items?$q$, $q${"A":"Only judicial powers","B":"Only party donations","C":"Only foreign aid","D":"Sources of local-government finance"}$q$::jsonb, $q$D$q$, $q$Intergovernmental allocations and local fees are possible local-government revenue sources.$q$),
  ($q$Public and Civil Service Administration$q$, $q$A ministry publishes service standards and a complaint process for delayed applications. What administrative value is strengthened?$q$, $q${"A":"Accountability to the public","B":"Secrecy without remedy","C":"Patronage appointments","D":"Unlimited discretion"}$q$::jsonb, $q$A$q$, $q$Public standards and complaints make officials answerable for service quality.$q$),
  ($q$Public and Civil Service Administration$q$, $q$Why can excessive political appointments weaken a career civil service?$q$, $q${"A":"They automatically improve all expertise","B":"They may replace merit and continuity with patronage","C":"They abolish the need for budgets","D":"They make all laws invalid"}$q$::jsonb, $q$B$q$, $q$Appointments based on loyalty rather than merit can undermine professional capacity and continuity.$q$),
  -- Pre-colonial Nigeria (12)
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$In a Hausa-Fulani emirate, who generally headed the emirate administration?$q$, $q${"A":"An elected modern president","B":"An Igbo age-grade leader","C":"The emir","D":"A colonial governor"}$q$::jsonb, $q$C$q$, $q$The emir was the central traditional authority in the emirate system.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Why did emirate administration usually permit coordinated decisions over a wide area?$q$, $q${"A":"Every village acted without common authority","B":"There were no district officials","C":"It relied only on private traders","D":"A hierarchy linked the emir to subordinate officials"}$q$::jsonb, $q$D$q$, $q$The emirate hierarchy connected central authority with district and local administrators.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$In the old Oyo political system, which council could act as a check on the Alaafin?$q$, $q${"A":"The Oyo Mesi","B":"A modern electoral commission","C":"The United Nations","D":"A colonial district office"}$q$::jsonb, $q$A$q$, $q$The Oyo Mesi was a council of chiefs that constrained the Alaafin's authority.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$A Yoruba oba consults chiefs before a major decision. What does this illustrate?$q$, $q${"A":"The absence of any ruler","B":"Consultative limits on royal power","C":"A modern presidential cabinet","D":"Rule by a foreign governor"}$q$::jsonb, $q$B$q$, $q$Traditional councils could advise and restrain a ruler rather than leaving all decisions to one person.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Many Igbo communities governed through elders, assemblies and age grades instead of one king. How is this structure often described?$q$, $q${"A":"Absolute monarchy","B":"Emirate hierarchy","C":"Decentralized or segmentary","D":"Colonial indirect rule"}$q$::jsonb, $q$C$q$, $q$Authority in many pre-colonial Igbo communities was distributed among several institutions.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$An age grade organizes communal work and helps enforce agreed rules in an Igbo village. What role is it performing?$q$, $q${"A":"Foreign diplomacy","B":"Modern party registration","C":"A national election","D":"Local civic administration"}$q$::jsonb, $q$D$q$, $q$Age grades could undertake community tasks and support local governance.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Why would a colonial policy built around existing single chiefs fit some emirates more readily than many Igbo villages?$q$, $q${"A":"Many Igbo villages lacked one comparable centralized ruler","B":"Igbo villages had no political institutions","C":"Emirates lacked any hierarchy","D":"Chiefs were unknown in all of Nigeria"}$q$::jsonb, $q$A$q$, $q$Indirect rule relied on existing centralized chiefs, while many Igbo communities had more dispersed authority.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Which institution was especially associated with traditional authority in the Sokoto emirate system?$q$, $q${"A":"A colonial legislative council","B":"Emirs within a wider caliphate hierarchy","C":"A modern city mayor","D":"A post-independence senate"}$q$::jsonb, $q$B$q$, $q$Emirates were linked within the Sokoto Caliphate's political and religious hierarchy.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$A Yoruba town's ruler and council disagree on a proposed levy. What does the council's ability to object show?$q$, $q${"A":"No political organization existed","B":"Only foreign officials had authority","C":"Traditional checks could constrain a ruler","D":"A legislature elected by universal suffrage"}$q$::jsonb, $q$C$q$, $q$Councils of chiefs could provide checks within traditional Yoruba governance.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Village assemblies allow adult members to debate community matters before elders act. Which feature is illustrated?$q$, $q${"A":"A hereditary national presidency","B":"A centralized emirate","C":"A colonial parliament","D":"Collective participation in local decisions"}$q$::jsonb, $q$D$q$, $q$Assemblies provided a forum for consultation and shared decisions in some communities.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Which statement best avoids an inaccurate generalization about pre-colonial Nigeria?$q$, $q${"A":"Political organization varied across Hausa-Fulani, Yoruba and Igbo societies","B":"Every community had the same single ruler","C":"No society had rules or institutions","D":"Only modern states can govern"}$q$::jsonb, $q$A$q$, $q$The syllabus studies several distinct systems, with different balances of centralized and dispersed authority.$q$),
  ($q$Pre-colonial Political Systems in Nigeria$q$, $q$Why did councils matter in many pre-colonial political systems?$q$, $q${"A":"They always replaced all rulers","B":"They could advise, represent interests and restrain decisions","C":"They were all elected by modern party ballot","D":"They controlled the United Nations"}$q$::jsonb, $q$B$q$, $q$Councils could bring additional voices and checks into decision-making, though their forms differed.$q$),
  -- Colonial administration (8)
  ($q$Colonial Administration$q$, $q$A colonial governor rules through an emir and existing local officials. Which British method is illustrated?$q$, $q${"A":"Direct universal suffrage","B":"French assimilation","C":"Indirect rule","D":"Confederal independence"}$q$::jsonb, $q$C$q$, $q$Indirect rule used existing local authorities to administer colonial policy.$q$),
  ($q$Colonial Administration$q$, $q$A colonial system seeks to make selected subjects adopt the colonizer's language and institutions. Which French policy does this resemble?$q$, $q${"A":"Indirect rule through emirs","B":"Full local sovereignty","C":"Federal devolution","D":"Assimilation"}$q$::jsonb, $q$D$q$, $q$Assimilation sought to spread French culture and institutions in colonial administration.$q$),
  ($q$Colonial Administration$q$, $q$A colonial authority adapts its policy to local customs instead of aiming to make every subject culturally French. Which French approach is closer?$q$, $q${"A":"Association","B":"Assimilation","C":"A unitary republic","D":"A constitutional referendum"}$q$::jsonb, $q$A$q$, $q$Association recognized some local institutions and practices while keeping colonial control.$q$),
  ($q$Colonial Administration$q$, $q$Why could indirect rule distort the role of a traditional ruler?$q$, $q${"A":"It always removed all rulers","B":"The ruler could become answerable upward to colonial officers rather than locally","C":"It automatically introduced universal voting","D":"It ended every local tax"}$q$::jsonb, $q$B$q$, $q$Colonial control could shift a ruler's incentives and accountability away from the community.$q$),
  ($q$Colonial Administration$q$, $q$A colonial protectorate controls external affairs while retaining some local institutions. Which feature marks the loss of independence?$q$, $q${"A":"The presence of a local market","B":"The use of local languages","C":"External sovereignty is constrained","D":"The existence of customary law"}$q$::jsonb, $q$C$q$, $q$Colonial control over foreign affairs limits a territory's sovereign authority.$q$),
  ($q$Colonial Administration$q$, $q$A colonial administration builds a railway mainly to move raw materials to a port. What question is most important when assessing its impact?$q$, $q${"A":"Whether tracks have a name","B":"Whether elections are never needed","C":"Whether every town is identical","D":"Whose economic interests the line primarily served"}$q$::jsonb, $q$D$q$, $q$Infrastructure can create benefits while also serving extraction; its distributional effects matter.$q$),
  ($q$Colonial Administration$q$, $q$A warrant chief is imposed where no comparable centralized office previously existed. Why might residents resist?$q$, $q${"A":"The imposed authority may lack local legitimacy","B":"It guarantees full self-government","C":"It ends all taxes automatically","D":"It makes elections unnecessary forever"}$q$::jsonb, $q$A$q$, $q$An externally appointed ruler may not have the community's traditional acceptance or accountability.$q$),
  ($q$Colonial Administration$q$, $q$Why did colonial administration sometimes rely on local intermediaries rather than employing a large number of foreign officials?$q$, $q${"A":"Colonial authorities had no policies","B":"It reduced administrative costs and used existing networks","C":"It gave colonies complete independence","D":"It abolished all hierarchy"}$q$::jsonb, $q$B$q$, $q$Using local authorities could make administration cheaper and extend control through known institutions.$q$),
  -- Nationalism in Nigeria (8)
  ($q$Nationalism in Nigeria$q$, $q$Newspapers criticize colonial exclusion and call for self-government. What movement do they help build?$q$, $q${"A":"Colonial assimilation","B":"Royal succession","C":"Nationalism","D":"Military occupation"}$q$::jsonb, $q$C$q$, $q$Nationalism seeks political self-determination and can grow through organized public criticism.$q$),
  ($q$Nationalism in Nigeria$q$, $q$Educated Nigerians form associations and petition for greater representation. Which mechanism of nationalist growth is illustrated?$q$, $q${"A":"Hereditary rule","B":"Withdrawal from public life","C":"Abolition of communication","D":"Organized political mobilization"}$q$::jsonb, $q$D$q$, $q$Associations and petitions bring demands for representation into collective political action.$q$),
  ($q$Nationalism in Nigeria$q$, $q$Why did returning soldiers after the Second World War sometimes strengthen anti-colonial demands?$q$, $q${"A":"Their experiences sharpened expectations of freedom and fair treatment","B":"They ended every political party","C":"They automatically became colonial governors","D":"They removed all newspapers"}$q$::jsonb, $q$A$q$, $q$War service and postwar expectations contributed to stronger demands for political change.$q$),
  ($q$Nationalism in Nigeria$q$, $q$Colonial officials allow only a narrow educated elite to vote. Why might nationalists object?$q$, $q${"A":"It gives everyone equal representation","B":"It excludes most people from political choice","C":"It guarantees full independence","D":"It abolishes property qualifications"}$q$::jsonb, $q$B$q$, $q$A restricted franchise limits participation and representation.$q$),
  ($q$Nationalism in Nigeria$q$, $q$A nationalist coalition includes trade unions, students and regional associations. What advantage can this bring?$q$, $q${"A":"It removes all internal differences","B":"It guarantees immediate independence","C":"It broadens support for self-government","D":"It ends the need for negotiation"}$q$::jsonb, $q$C$q$, $q$Different organizations can mobilize wider sections of society behind reform.$q$),
  ($q$Nationalism in Nigeria$q$, $q$A newspaper exposes unequal colonial employment rules with evidence. Which nationalist tool is it using?$q$, $q${"A":"A secret military coup","B":"A hereditary council","C":"A tax exemption","D":"Public opinion and the press"}$q$::jsonb, $q$D$q$, $q$The press can publicize injustice and rally support for political change.$q$),
  ($q$Nationalism in Nigeria$q$, $q$Nationalists demand a timetable for Nigerians to control national institutions. What is their immediate political aim?$q$, $q${"A":"Self-government","B":"Permanent colonial rule","C":"Abolition of citizenship","D":"Government without institutions"}$q$::jsonb, $q$A$q$, $q$Self-government means political authority is exercised by the country's own people and institutions.$q$),
  ($q$Nationalism in Nigeria$q$, $q$Why might a nationalist movement oppose both foreign rule and discrimination among local groups?$q$, $q${"A":"Both increase external military power","B":"A durable independent state needs shared citizenship and inclusion","C":"Both eliminate elections automatically","D":"A nation has no internal diversity"}$q$::jsonb, $q$B$q$, $q$Independence alone does not guarantee inclusive citizenship; internal cohesion also matters.$q$),
  -- Constitutional development in Nigeria (16)
  ($q$Constitutional Development in Nigeria$q$, $q$Which constitutional step first introduced a limited elective principle to colonial Nigeria's Legislative Council?$q$, $q${"A":"The Richards Constitution of 1946","B":"The Lyttleton Constitution of 1954","C":"The Clifford Constitution of 1922","D":"The Republican Constitution of 1963"}$q$::jsonb, $q$C$q$, $q$The Clifford Constitution introduced a small number of elected seats, but participation remained very restricted.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Why did Clifford's 1922 elective provision fall short of broad representative government?$q$, $q${"A":"It gave all adults a vote","B":"It removed the governor's powers","C":"It made every province equal","D":"Only a small electorate and few seats were covered"}$q$::jsonb, $q$D$q$, $q$The franchise and number of elected seats were narrow, so most Nigerians had no direct electoral voice.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Which 1946 constitution gave regional institutions a clearer place in colonial Nigerian government?$q$, $q${"A":"Richards","B":"Clifford","C":"Republican","D":"1999"}$q$::jsonb, $q$A$q$, $q$The Richards Constitution strengthened regional arrangements and included the North in central legislative structures.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$A constitution is drafted with little consultation of Nigerians, leading to criticism despite its regional reforms. Which constitution best fits?$q$, $q${"A":"Macpherson 1951","B":"Richards 1946","C":"Lyttleton 1954","D":"Republican 1963"}$q$::jsonb, $q$B$q$, $q$The Richards Constitution was criticized for insufficient Nigerian consultation.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Which constitution followed an unusually wide process of public consultation before adoption in colonial Nigeria?$q$, $q${"A":"Clifford 1922","B":"Richards 1946","C":"Macpherson 1951","D":"Independence 1960"}$q$::jsonb, $q$C$q$, $q$The Macpherson Constitution was notable for consultations from local to national levels.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Why was the Macpherson arrangement not yet full independence?$q$, $q${"A":"It had no Nigerian participants","B":"It abolished regional institutions","C":"It created a republic","D":"Colonial authorities still retained ultimate powers"}$q$::jsonb, $q$D$q$, $q$Expanded participation did not remove the colonial government's overriding authority.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Which pre-independence constitution is most closely linked to a clearer federal division of central and regional powers?$q$, $q${"A":"Lyttleton 1954","B":"Clifford 1922","C":"Richards 1946","D":"Macpherson 1951"}$q$::jsonb, $q$A$q$, $q$The Lyttleton Constitution established a more explicit federal structure.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Why did a defined division of powers matter under the 1954 federal arrangement?$q$, $q${"A":"It removed all regional governments","B":"It clarified which level could legislate on different matters","C":"It made Nigeria a monarchy ruled by emirs","D":"It replaced all courts with ministers"}$q$::jsonb, $q$B$q$, $q$Federal lists and institutional arrangements helped distinguish central and regional authority.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Nigeria became independent in 1960 while retaining a governor-general as representative of the monarch. Which constitution established that arrangement?$q$, $q${"A":"Clifford 1922","B":"Richards 1946","C":"Independence Constitution 1960","D":"1999 Constitution"}$q$::jsonb, $q$C$q$, $q$The 1960 Independence Constitution retained the monarch as head of state, represented locally by a governor-general.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$What did independence in 1960 change most fundamentally compared with the colonial constitutions?$q$, $q${"A":"All regional governments disappeared","B":"The constitution ceased to exist","C":"Nigeria became a military state","D":"Nigeria gained sovereign self-government"}$q$::jsonb, $q$D$q$, $q$Independence ended colonial sovereignty and placed national government under Nigerian authority.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$What was a defining change when Nigeria adopted a republican constitution in 1963?$q$, $q${"A":"A Nigerian president replaced the monarch as head of state","B":"The country returned to colonial rule","C":"All parliamentary institutions were abolished","D":"The federation ceased to exist"}$q$::jsonb, $q$A$q$, $q$Republican status replaced the British monarch's head-of-state role with a Nigerian president.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Which statement correctly compares Nigeria's 1960 and 1963 arrangements?$q$, $q${"A":"Both were presidential republics","B":"The 1963 republic retained parliamentary government while changing the head of state","C":"The 1960 constitution was a military decree","D":"The 1963 constitution abolished elections"}$q$::jsonb, $q$B$q$, $q$The move to a republic changed the head of state, not the parliamentary character of the executive.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Which constitution introduced a US-style presidential executive for Nigeria's Second Republic?$q$, $q${"A":"Clifford 1922","B":"Independence 1960","C":"1979 Constitution","D":"Richards 1946"}$q$::jsonb, $q$C$q$, $q$The 1979 Constitution replaced the earlier parliamentary model with a presidential one.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Why should a student avoid saying the 1989 constitution governed a completed, lasting civilian Third Republic?$q$, $q${"A":"There was no plan for civilian rule","B":"The 1989 document was the first colonial constitution","C":"The document created a hereditary monarchy","D":"The national civilian transition was not fully completed"}$q$::jsonb, $q$D$q$, $q$The planned transition under the 1989 Constitution did not produce a completed lasting national civilian republic.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$Under the 1999 Constitution, national and state governments exercise constitutionally assigned powers. Which principle is this?$q$, $q${"A":"Federalism","B":"Colonial indirect rule","C":"Absolute monarchy","D":"A confederation of independent states"}$q$::jsonb, $q$A$q$, $q$The 1999 Constitution establishes a federation with powers allocated among levels of government.$q$),
  ($q$Constitutional Development in Nigeria$q$, $q$A bill passes through the Senate and House of Representatives under the 1999 Constitution. What does this show about the National Assembly?$q$, $q${"A":"It has no legislative role","B":"It is bicameral","C":"It is a court","D":"It is a single-house cabinet"}$q$::jsonb, $q$B$q$, $q$The National Assembly has two chambers: the Senate and the House of Representatives.$q$),
  -- Development of Nigerian political parties (6)
  ($q$Development of Political Parties in Nigeria$q$, $q$A nationalist party seeks support across several Nigerian regions rather than from only one town. What advantage does this offer?$q$, $q${"A":"It guarantees every election victory","B":"It removes all policy disagreements","C":"It can build a broader coalition for self-government","D":"It abolishes regional concerns"}$q$::jsonb, $q$C$q$, $q$Cross-regional organization can connect more communities to a national political demand.$q$),
  ($q$Development of Political Parties in Nigeria$q$, $q$Which activity most clearly distinguishes a political party from a cultural society during Nigeria's move toward independence?$q$, $q${"A":"Holding social gatherings","B":"Publishing a newsletter","C":"Keeping membership records","D":"Nominating candidates to win public office"}$q$::jsonb, $q$D$q$, $q$Seeking elective office through candidates is a defining party activity.$q$),
  ($q$Development of Political Parties in Nigeria$q$, $q$A party helps supporters understand a proposed constitution before an election. What role is it performing?$q$, $q${"A":"Political education","B":"Court sentencing","C":"Currency issuance","D":"Colonial taxation"}$q$::jsonb, $q$A$q$, $q$Parties explain issues and choices to voters as part of political mobilization.$q$),
  ($q$Development of Political Parties in Nigeria$q$, $q$Parties draw money from members and public donations. Why should the sources be disclosed?$q$, $q${"A":"To eliminate every donation","B":"To make political financing accountable","C":"To replace the ballot","D":"To end all campaigns"}$q$::jsonb, $q$B$q$, $q$Disclosure helps citizens assess influence and compliance with finance rules.$q$),
  ($q$Development of Political Parties in Nigeria$q$, $q$During a constitutional conference, parties disagree about the allocation of regional powers. What is the underlying issue?$q$, $q${"A":"Whether voting is secret","B":"How to appoint every judge","C":"How to balance regional autonomy with national unity","D":"How to abolish the constitution"}$q$::jsonb, $q$C$q$, $q$Federal design requires negotiation between regional self-government and shared national authority.$q$),
  ($q$Development of Political Parties in Nigeria$q$, $q$A party wins regional seats but must work with another party to govern nationally. What political skill becomes important?$q$, $q${"A":"Refusing every negotiation","B":"Ending parliamentary debate","C":"Replacing elections with decrees","D":"Coalition bargaining"}$q$::jsonb, $q$D$q$, $q$Coalition bargaining lets parties combine legislative support and agree on government priorities.$q$),
  -- Military rule in Nigeria (6)
  ($q$Military Rule in Nigeria$q$, $q$Soldiers remove an elected government outside the constitutional succession process. What has occurred?$q$, $q${"A":"A coup d'état","B":"A referendum","C":"A judicial appeal","D":"A coalition agreement"}$q$::jsonb, $q$A$q$, $q$A coup seizes political power by force rather than through the lawful constitutional route.$q$),
  ($q$Military Rule in Nigeria$q$, $q$A military council governs by decrees and suspends parts of the constitution. What is the key democratic concern?$q$, $q${"A":"Too much judicial independence","B":"Reduced constitutional checks and representation","C":"Too many competitive elections","D":"Excessive local consultation"}$q$::jsonb, $q$B$q$, $q$Suspending constitutional limits and elected institutions weakens democratic accountability.$q$),
  ($q$Military Rule in Nigeria$q$, $q$Why can a promise of a future election fail to make current military rule democratic?$q$, $q${"A":"Elections are never democratic","B":"A timetable abolishes all rights","C":"Present authority still lacks an elected mandate and full accountability","D":"Military officers cannot read constitutions"}$q$::jsonb, $q$C$q$, $q$A proposed transition does not substitute for current representative and accountable government.$q$),
  ($q$Military Rule in Nigeria$q$, $q$A military government centralizes decisions previously taken by elected regional bodies. Which effect is most likely?$q$, $q${"A":"Regional autonomy automatically expands","B":"Every citizen gains a veto","C":"Courts become legislatures","D":"Subnational political discretion is reduced"}$q$::jsonb, $q$D$q$, $q$Centralized military command can reduce the independent authority of regional institutions.$q$),
  ($q$Military Rule in Nigeria$q$, $q$A transition plan allows parties to organize and schedules a transfer to elected leaders. What is its stated objective?$q$, $q${"A":"Restoration of civilian government","B":"Permanent rule by decree","C":"Abolition of elections","D":"Creation of a hereditary throne"}$q$::jsonb, $q$A$q$, $q$A genuine transition aims to replace military command with constitutionally elected civilian authority.$q$),
  ($q$Military Rule in Nigeria$q$, $q$Which institution is especially important for testing whether detentions under military rule are lawful?$q$, $q${"A":"A campaign committee","B":"An independent judiciary","C":"A party treasurer","D":"A trade fair"}$q$::jsonb, $q$B$q$, $q$Independent courts can hear challenges to detention where their jurisdiction is preserved.$q$),
  -- Nigerian federalism (5)
  ($q$Federalism in Nigeria$q$, $q$A dispute asks whether a policy belongs to national or state lawmakers. Which document should be consulted first?$q$, $q${"A":"A newspaper advert","B":"A party song","C":"The constitution's division of powers","D":"A private contract unrelated to government"}$q$::jsonb, $q$C$q$, $q$The constitution assigns subjects to different levels of government.$q$),
  ($q$Federalism in Nigeria$q$, $q$Why might Nigeria's federal system reserve some functions for the national government?$q$, $q${"A":"States have no interests","B":"Local councils are foreign countries","C":"All issues are identical","D":"Some matters require one country-wide policy"}$q$::jsonb, $q$D$q$, $q$Nationwide concerns can require central coordination while other matters allow regional decisions.$q$),
  ($q$Federalism in Nigeria$q$, $q$States ask for a fairer share of revenues collected nationally. Which federal issue is this?$q$, $q${"A":"Fiscal federalism and revenue allocation","B":"Judicial sentencing","C":"Diplomatic immunity","D":"Hereditary succession"}$q$::jsonb, $q$A$q$, $q$Fiscal federalism concerns how revenue and spending responsibilities are shared among levels of government.$q$),
  ($q$Federalism in Nigeria$q$, $q$A state law conflicts with a valid federal law on a matter where federal law prevails. What is the likely result?$q$, $q${"A":"Both laws vanish automatically","B":"The state law yields to the valid federal law to the extent of conflict","C":"A local party decides by slogan","D":"The constitution becomes irrelevant"}$q$::jsonb, $q$B$q$, $q$Constitutional supremacy rules determine which valid law prevails when jurisdictions overlap.$q$),
  ($q$Federalism in Nigeria$q$, $q$What challenge can arise when two levels of government have overlapping service responsibilities?$q$, $q${"A":"Every service becomes free","B":"All courts close","C":"Coordination and accountability may become unclear","D":"No budget is required"}$q$::jsonb, $q$C$q$, $q$Overlapping functions can create duplication or disputes about who should deliver and finance a service.$q$),
  -- Nigerian foreign policy (7)
  ($q$Nigeria's Foreign Policy$q$, $q$Nigeria chooses a diplomatic position after weighing security, trade and citizens abroad. What is guiding the decision?$q$, $q${"A":"A local council bylaw","B":"A school timetable","C":"A private inheritance rule","D":"National interest"}$q$::jsonb, $q$D$q$, $q$Foreign policy pursues perceived national interests across external relationships.$q$),
  ($q$Nigeria's Foreign Policy$q$, $q$Nigeria works with neighbouring states to reduce border trade barriers. Which foreign-policy method is this?$q$, $q${"A":"Regional cooperation","B":"Complete isolation","C":"A domestic court appeal","D":"A local zoning decision"}$q$::jsonb, $q$A$q$, $q$Cooperation with neighbours is a regional approach to shared economic goals.$q$),
  ($q$Nigeria's Foreign Policy$q$, $q$A government prefers to judge each international issue on its merits rather than automatically follow one major-power bloc. Which approach is closest?$q$, $q${"A":"Colonial rule","B":"Non-alignment","C":"Hereditary monarchy","D":"Domestic federalism"}$q$::jsonb, $q$B$q$, $q$Non-alignment avoids automatic attachment to a rival power bloc while permitting issue-by-issue choices.$q$),
  ($q$Nigeria's Foreign Policy$q$, $q$Nigeria supports mediation in a neighbouring country because instability may spread across borders. What concern links the two states?$q$, $q${"A":"A shared cabinet","B":"One national constitution","C":"Regional security","D":"The abolition of sovereignty"}$q$::jsonb, $q$C$q$, $q$Instability in one state can affect the security of nearby states.$q$),
  ($q$Nigeria's Foreign Policy$q$, $q$A diplomat negotiates an agreement but it still requires domestic approval before taking effect. What does this show?$q$, $q${"A":"Diplomats make domestic law alone","B":"Foreign policy has no legal process","C":"Only foreign courts matter","D":"External commitments can require constitutional domestic procedures"}$q$::jsonb, $q$D$q$, $q$Treaty commitments often depend on the state's constitutional rules for approval or implementation.$q$),
  ($q$Nigeria's Foreign Policy$q$, $q$Nigeria offers humanitarian help during a crisis elsewhere in Africa. Which stated emphasis of its foreign policy may this express?$q$, $q${"A":"African cooperation and solidarity","B":"Permanent isolation","C":"Abolition of diplomacy","D":"Control of another state's elections"}$q$::jsonb, $q$A$q$, $q$Support for other African states can reflect an Africa-centred diplomatic priority.$q$),
  ($q$Nigeria's Foreign Policy$q$, $q$A country adjusts its foreign trade policy after a fall in export earnings. What does this illustrate?$q$, $q${"A":"Foreign policy cannot change","B":"Economic conditions can shape external policy","C":"Only cultural events matter","D":"Domestic resources are irrelevant"}$q$::jsonb, $q$B$q$, $q$Trade and revenue conditions can affect a country's external priorities and bargaining choices.$q$),
  -- International organizations (10)
  ($q$International Organizations$q$, $q$States debate a worldwide health emergency in a forum where each UN member has a seat. Which organ is the broad deliberative forum?$q$, $q${"A":"A national cabinet","B":"A local court","C":"The UN General Assembly","D":"A regional city council"}$q$::jsonb, $q$C$q$, $q$The General Assembly includes all UN member states for discussion and resolutions.$q$),
  ($q$International Organizations$q$, $q$A threat to international peace is brought before the UN body with primary responsibility for peace and security. Which body is it?$q$, $q${"A":"The Secretariat alone","B":"The General Assembly's library","C":"A national parliament","D":"The Security Council"}$q$::jsonb, $q$D$q$, $q$The Security Council has primary UN responsibility for maintaining international peace and security.$q$),
  ($q$International Organizations$q$, $q$A West African trader benefits from member states reducing barriers within ECOWAS. Which aim is being advanced?$q$, $q${"A":"Regional economic integration","B":"An end to all national governments","C":"A worldwide single parliament","D":"A ban on local production"}$q$::jsonb, $q$A$q$, $q$ECOWAS seeks stronger economic cooperation and integration among West African members.$q$),
  ($q$International Organizations$q$, $q$Member countries coordinate action against a cross-border conflict through ECOWAS. Which wider purpose does this serve?$q$, $q${"A":"Abolishing all diplomacy","B":"Regional peace and security","C":"Replacing every national court","D":"Ending all trade"}$q$::jsonb, $q$B$q$, $q$Regional stability is important to cooperation and is a field of ECOWAS action.$q$),
  ($q$International Organizations$q$, $q$African governments work through the African Union on shared continental concerns. What kind of body is the AU?$q$, $q${"A":"A private company","B":"A Nigerian state government","C":"A continental intergovernmental organization","D":"A colonial governor's office"}$q$::jsonb, $q$C$q$, $q$The AU brings African states together for continental cooperation.$q$),
  ($q$International Organizations$q$, $q$An African development initiative encourages African states to plan and lead their own growth strategies. Which programme is most closely associated with the AU framework?$q$, $q${"A":"A colonial trading monopoly","B":"A national election petition","C":"A private cabinet","D":"NEPAD"}$q$::jsonb, $q$D$q$, $q$NEPAD is an African-led development partnership associated with continental cooperation.$q$),
  ($q$International Organizations$q$, $q$Countries with historical links to Britain cooperate voluntarily on education and governance. Which association is described?$q$, $q${"A":"The Commonwealth of Nations","B":"A Nigerian local council","C":"The UN Security Council only","D":"A military junta"}$q$::jsonb, $q$A$q$, $q$The Commonwealth is a voluntary association of states, many with historical British links.$q$),
  ($q$International Organizations$q$, $q$Why can an international organization's decision be hard to enforce when members disagree?$q$, $q${"A":"It owns every state's courts","B":"It often depends on member cooperation and agreed powers","C":"Its members have no governments","D":"It cannot hold meetings"}$q$::jsonb, $q$B$q$, $q$Intergovernmental bodies act within powers granted by states and often need members to implement decisions.$q$),
  ($q$International Organizations$q$, $q$A disease crosses borders, so several states share surveillance information through a UN-linked body. What advantage of international cooperation is shown?$q$, $q${"A":"It removes every national health service","B":"It guarantees no future outbreak","C":"Shared information helps manage transnational problems","D":"It makes borders legally disappear"}$q$::jsonb, $q$C$q$, $q$Cross-border problems can be tackled more effectively when states coordinate information and responses.$q$),
  ($q$International Organizations$q$, $q$A small state joins a regional body to negotiate trade rules with larger partners. What possible benefit does membership bring?$q$, $q${"A":"Automatic control of every partner","B":"A guarantee that all disputes end","C":"Freedom from every domestic law","D":"A stronger collective bargaining voice"}$q$::jsonb, $q$D$q$, $q$Acting with neighbours can increase bargaining leverage, although benefits are not guaranteed.$q$)
)
insert into public.questions (
  subject_id, exam_type, source, year, topic,
  prompt, options, correct_answer, explanation
)
select subject.id, subject.exam_type, $q$original$q$, null,
       candidate.topic, candidate.prompt, candidate.options,
       candidate.correct_answer, candidate.explanation
from candidates as candidate
cross join public.subjects as subject
where subject.id = 'a628f321-1de0-4a78-baf4-a8aeca29f836'::uuid
  and lower(subject.exam_type::text) = 'waec'
  and not exists (
    select 1 from public.questions as existing
    where existing.subject_id = subject.id
      and existing.prompt = candidate.prompt
  );

commit;
