-- Track accepted PWA installations for admin analytics.
-- The installation_id is generated by the browser and prevents duplicate
-- events from the same browser installation.

create table if not exists public.pwa_installations (
  id uuid primary key default gen_random_uuid(),
  installation_id uuid not null unique,
  user_id uuid references public.users(id) on delete set null,
  platform text not null default 'unknown'
    check (platform in ('android', 'ios', 'desktop', 'unknown')),
  installed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.pwa_installations enable row level security;

create index if not exists pwa_installations_installed_at_idx
  on public.pwa_installations(installed_at desc);

create index if not exists pwa_installations_user_id_idx
  on public.pwa_installations(user_id)
  where user_id is not null;

-- Installation records are written by the server with the service-role client.
-- No public read or insert policy is granted.
